/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.EdFiGradebookEntryLearningObjective;
import org.edfi.model.resource.EdFiGradebookEntryLearningStandard;
import org.edfi.model.resource.EdFiGradingPeriodReference;
import org.edfi.model.resource.EdFiSectionReference;
import org.edfi.model.resource.GradebookEntryExtensions;
import org.joda.time.LocalDate;


/**
 * EdFiGradebookEntry
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class EdFiGradebookEntry   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("dateAssigned")
  private LocalDate dateAssigned = null;

  @SerializedName("gradebookEntryTitle")
  private String gradebookEntryTitle = null;

  @SerializedName("gradingPeriodReference")
  private EdFiGradingPeriodReference gradingPeriodReference = null;

  @SerializedName("sectionReference")
  private EdFiSectionReference sectionReference = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("gradebookEntryTypeDescriptor")
  private String gradebookEntryTypeDescriptor = null;

  @SerializedName("learningObjectives")
  private List<EdFiGradebookEntryLearningObjective> learningObjectives = new ArrayList<EdFiGradebookEntryLearningObjective>();

  @SerializedName("learningStandards")
  private List<EdFiGradebookEntryLearningStandard> learningStandards = new ArrayList<EdFiGradebookEntryLearningStandard>();

  @SerializedName("_etag")
  private String etag = null;

  @SerializedName("_ext")
  private GradebookEntryExtensions ext = null;

  public EdFiGradebookEntry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EdFiGradebookEntry dateAssigned(LocalDate dateAssigned) {
    this.dateAssigned = dateAssigned;
    return this;
  }

   /**
   * The date the assignment, homework, or assessment was assigned or executed.
   * @return dateAssigned
  **/
  @ApiModelProperty(example = "null", required = true, value = "The date the assignment, homework, or assessment was assigned or executed.")
  public LocalDate getDateAssigned() {
    return dateAssigned;
  }

  public void setDateAssigned(LocalDate dateAssigned) {
    this.dateAssigned = dateAssigned;
  }

  public EdFiGradebookEntry gradebookEntryTitle(String gradebookEntryTitle) {
    this.gradebookEntryTitle = gradebookEntryTitle;
    return this;
  }

   /**
   * The name or title of the activity to be recorded in the GradebookEntry.
   * @return gradebookEntryTitle
  **/
  @ApiModelProperty(example = "null", required = true, value = "The name or title of the activity to be recorded in the GradebookEntry.")
  public String getGradebookEntryTitle() {
    return gradebookEntryTitle;
  }

  public void setGradebookEntryTitle(String gradebookEntryTitle) {
    this.gradebookEntryTitle = gradebookEntryTitle;
  }

  public EdFiGradebookEntry gradingPeriodReference(EdFiGradingPeriodReference gradingPeriodReference) {
    this.gradingPeriodReference = gradingPeriodReference;
    return this;
  }

   /**
   * Get gradingPeriodReference
   * @return gradingPeriodReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiGradingPeriodReference getGradingPeriodReference() {
    return gradingPeriodReference;
  }

  public void setGradingPeriodReference(EdFiGradingPeriodReference gradingPeriodReference) {
    this.gradingPeriodReference = gradingPeriodReference;
  }

  public EdFiGradebookEntry sectionReference(EdFiSectionReference sectionReference) {
    this.sectionReference = sectionReference;
    return this;
  }

   /**
   * Get sectionReference
   * @return sectionReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiSectionReference getSectionReference() {
    return sectionReference;
  }

  public void setSectionReference(EdFiSectionReference sectionReference) {
    this.sectionReference = sectionReference;
  }

  public EdFiGradebookEntry description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the assignment, homework, or classroom assessment.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "A description of the assignment, homework, or classroom assessment.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EdFiGradebookEntry gradebookEntryTypeDescriptor(String gradebookEntryTypeDescriptor) {
    this.gradebookEntryTypeDescriptor = gradebookEntryTypeDescriptor;
    return this;
  }

   /**
   * The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.
   * @return gradebookEntryTypeDescriptor
  **/
  @ApiModelProperty(example = "null", value = "The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.")
  public String getGradebookEntryTypeDescriptor() {
    return gradebookEntryTypeDescriptor;
  }

  public void setGradebookEntryTypeDescriptor(String gradebookEntryTypeDescriptor) {
    this.gradebookEntryTypeDescriptor = gradebookEntryTypeDescriptor;
  }

  public EdFiGradebookEntry learningObjectives(List<EdFiGradebookEntryLearningObjective> learningObjectives) {
    this.learningObjectives = learningObjectives;
    return this;
  }

  public EdFiGradebookEntry addLearningObjectivesItem(EdFiGradebookEntryLearningObjective learningObjectivesItem) {
    this.learningObjectives.add(learningObjectivesItem);
    return this;
  }

   /**
   * An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.
   * @return learningObjectives
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.")
  public List<EdFiGradebookEntryLearningObjective> getLearningObjectives() {
    return learningObjectives;
  }

  public void setLearningObjectives(List<EdFiGradebookEntryLearningObjective> learningObjectives) {
    this.learningObjectives = learningObjectives;
  }

  public EdFiGradebookEntry learningStandards(List<EdFiGradebookEntryLearningStandard> learningStandards) {
    this.learningStandards = learningStandards;
    return this;
  }

  public EdFiGradebookEntry addLearningStandardsItem(EdFiGradebookEntryLearningStandard learningStandardsItem) {
    this.learningStandards.add(learningStandardsItem);
    return this;
  }

   /**
   * An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.
   * @return learningStandards
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.")
  public List<EdFiGradebookEntryLearningStandard> getLearningStandards() {
    return learningStandards;
  }

  public void setLearningStandards(List<EdFiGradebookEntryLearningStandard> learningStandards) {
    this.learningStandards = learningStandards;
  }

  public EdFiGradebookEntry etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }

  public EdFiGradebookEntry ext(GradebookEntryExtensions ext) {
    this.ext = ext;
    return this;
  }

   /**
   * Get ext
   * @return ext
  **/
  @ApiModelProperty(example = "null", value = "")
  public GradebookEntryExtensions getExt() {
    return ext;
  }

  public void setExt(GradebookEntryExtensions ext) {
    this.ext = ext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiGradebookEntry edFiGradebookEntry = (EdFiGradebookEntry) o;
    return Objects.equals(this.id, edFiGradebookEntry.id) &&
        Objects.equals(this.dateAssigned, edFiGradebookEntry.dateAssigned) &&
        Objects.equals(this.gradebookEntryTitle, edFiGradebookEntry.gradebookEntryTitle) &&
        Objects.equals(this.gradingPeriodReference, edFiGradebookEntry.gradingPeriodReference) &&
        Objects.equals(this.sectionReference, edFiGradebookEntry.sectionReference) &&
        Objects.equals(this.description, edFiGradebookEntry.description) &&
        Objects.equals(this.gradebookEntryTypeDescriptor, edFiGradebookEntry.gradebookEntryTypeDescriptor) &&
        Objects.equals(this.learningObjectives, edFiGradebookEntry.learningObjectives) &&
        Objects.equals(this.learningStandards, edFiGradebookEntry.learningStandards) &&
        Objects.equals(this.etag, edFiGradebookEntry.etag) &&
        Objects.equals(this.ext, edFiGradebookEntry.ext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dateAssigned, gradebookEntryTitle, gradingPeriodReference, sectionReference, description, gradebookEntryTypeDescriptor, learningObjectives, learningStandards, etag, ext);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiGradebookEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dateAssigned: ").append(toIndentedString(dateAssigned)).append("\n");
    sb.append("    gradebookEntryTitle: ").append(toIndentedString(gradebookEntryTitle)).append("\n");
    sb.append("    gradingPeriodReference: ").append(toIndentedString(gradingPeriodReference)).append("\n");
    sb.append("    sectionReference: ").append(toIndentedString(sectionReference)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    gradebookEntryTypeDescriptor: ").append(toIndentedString(gradebookEntryTypeDescriptor)).append("\n");
    sb.append("    learningObjectives: ").append(toIndentedString(learningObjectives)).append("\n");
    sb.append("    learningStandards: ").append(toIndentedString(learningStandards)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    ext: ").append(toIndentedString(ext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

