/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod;


/**
 * EdFiStudentEducationOrganizationAssociationStudentIndicator
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class EdFiStudentEducationOrganizationAssociationStudentIndicator   {
  @SerializedName("indicatorName")
  private String indicatorName = null;

  @SerializedName("designatedBy")
  private String designatedBy = null;

  @SerializedName("indicator")
  private String indicator = null;

  @SerializedName("indicatorGroup")
  private String indicatorGroup = null;

  @SerializedName("periods")
  private List<EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod> periods = new ArrayList<EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod>();

  public EdFiStudentEducationOrganizationAssociationStudentIndicator indicatorName(String indicatorName) {
    this.indicatorName = indicatorName;
    return this;
  }

   /**
   * The name of the indicator or metric.
   * @return indicatorName
  **/
  @ApiModelProperty(example = "null", required = true, value = "The name of the indicator or metric.")
  public String getIndicatorName() {
    return indicatorName;
  }

  public void setIndicatorName(String indicatorName) {
    this.indicatorName = indicatorName;
  }

  public EdFiStudentEducationOrganizationAssociationStudentIndicator designatedBy(String designatedBy) {
    this.designatedBy = designatedBy;
    return this;
  }

   /**
   * The person, organization, or department that designated the program association.
   * @return designatedBy
  **/
  @ApiModelProperty(example = "null", value = "The person, organization, or department that designated the program association.")
  public String getDesignatedBy() {
    return designatedBy;
  }

  public void setDesignatedBy(String designatedBy) {
    this.designatedBy = designatedBy;
  }

  public EdFiStudentEducationOrganizationAssociationStudentIndicator indicator(String indicator) {
    this.indicator = indicator;
    return this;
  }

   /**
   * The value of the indicator or metric.
   * @return indicator
  **/
  @ApiModelProperty(example = "null", required = true, value = "The value of the indicator or metric.")
  public String getIndicator() {
    return indicator;
  }

  public void setIndicator(String indicator) {
    this.indicator = indicator;
  }

  public EdFiStudentEducationOrganizationAssociationStudentIndicator indicatorGroup(String indicatorGroup) {
    this.indicatorGroup = indicatorGroup;
    return this;
  }

   /**
   * The name for a group of indicators.
   * @return indicatorGroup
  **/
  @ApiModelProperty(example = "null", value = "The name for a group of indicators.")
  public String getIndicatorGroup() {
    return indicatorGroup;
  }

  public void setIndicatorGroup(String indicatorGroup) {
    this.indicatorGroup = indicatorGroup;
  }

  public EdFiStudentEducationOrganizationAssociationStudentIndicator periods(List<EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod> periods) {
    this.periods = periods;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociationStudentIndicator addPeriodsItem(EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod periodsItem) {
    this.periods.add(periodsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationStudentIndicatorPeriods. The time periods for which the indicator was effective.
   * @return periods
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of studentEducationOrganizationAssociationStudentIndicatorPeriods. The time periods for which the indicator was effective.")
  public List<EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod> getPeriods() {
    return periods;
  }

  public void setPeriods(List<EdFiStudentEducationOrganizationAssociationStudentIndicatorPeriod> periods) {
    this.periods = periods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiStudentEducationOrganizationAssociationStudentIndicator edFiStudentEducationOrganizationAssociationStudentIndicator = (EdFiStudentEducationOrganizationAssociationStudentIndicator) o;
    return Objects.equals(this.indicatorName, edFiStudentEducationOrganizationAssociationStudentIndicator.indicatorName) &&
        Objects.equals(this.designatedBy, edFiStudentEducationOrganizationAssociationStudentIndicator.designatedBy) &&
        Objects.equals(this.indicator, edFiStudentEducationOrganizationAssociationStudentIndicator.indicator) &&
        Objects.equals(this.indicatorGroup, edFiStudentEducationOrganizationAssociationStudentIndicator.indicatorGroup) &&
        Objects.equals(this.periods, edFiStudentEducationOrganizationAssociationStudentIndicator.periods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indicatorName, designatedBy, indicator, indicatorGroup, periods);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiStudentEducationOrganizationAssociationStudentIndicator {\n");
    
    sb.append("    indicatorName: ").append(toIndentedString(indicatorName)).append("\n");
    sb.append("    designatedBy: ").append(toIndentedString(designatedBy)).append("\n");
    sb.append("    indicator: ").append(toIndentedString(indicator)).append("\n");
    sb.append("    indicatorGroup: ").append(toIndentedString(indicatorGroup)).append("\n");
    sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

