/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.EdFiLearningStandardAcademicSubject;
import org.edfi.model.resource.EdFiLearningStandardContentStandard;
import org.edfi.model.resource.EdFiLearningStandardGradeLevel;
import org.edfi.model.resource.EdFiLearningStandardIdentificationCode;
import org.edfi.model.resource.EdFiLearningStandardPrerequisiteLearningStandard;
import org.edfi.model.resource.EdFiLearningStandardReference;


/**
 * EdFiLearningStandard
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class EdFiLearningStandard   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("academicSubjects")
  private List<EdFiLearningStandardAcademicSubject> academicSubjects = new ArrayList<EdFiLearningStandardAcademicSubject>();

  @SerializedName("gradeLevels")
  private List<EdFiLearningStandardGradeLevel> gradeLevels = new ArrayList<EdFiLearningStandardGradeLevel>();

  @SerializedName("learningStandardId")
  private String learningStandardId = null;

  @SerializedName("parentLearningStandardReference")
  private EdFiLearningStandardReference parentLearningStandardReference = null;

  @SerializedName("contentStandard")
  private EdFiLearningStandardContentStandard contentStandard = null;

  @SerializedName("courseTitle")
  private String courseTitle = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("identificationCodes")
  private List<EdFiLearningStandardIdentificationCode> identificationCodes = new ArrayList<EdFiLearningStandardIdentificationCode>();

  @SerializedName("learningStandardCategoryDescriptor")
  private String learningStandardCategoryDescriptor = null;

  @SerializedName("learningStandardItemCode")
  private String learningStandardItemCode = null;

  @SerializedName("namespace")
  private String namespace = null;

  @SerializedName("prerequisiteLearningStandards")
  private List<EdFiLearningStandardPrerequisiteLearningStandard> prerequisiteLearningStandards = new ArrayList<EdFiLearningStandardPrerequisiteLearningStandard>();

  @SerializedName("successCriteria")
  private String successCriteria = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("_etag")
  private String etag = null;

  public EdFiLearningStandard id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EdFiLearningStandard academicSubjects(List<EdFiLearningStandardAcademicSubject> academicSubjects) {
    this.academicSubjects = academicSubjects;
    return this;
  }

  public EdFiLearningStandard addAcademicSubjectsItem(EdFiLearningStandardAcademicSubject academicSubjectsItem) {
    this.academicSubjects.add(academicSubjectsItem);
    return this;
  }

   /**
   * An unordered collection of learningStandardAcademicSubjects. Subject area for the LearningStandard.
   * @return academicSubjects
  **/
  @ApiModelProperty(example = "null", required = true, value = "An unordered collection of learningStandardAcademicSubjects. Subject area for the LearningStandard.")
  public List<EdFiLearningStandardAcademicSubject> getAcademicSubjects() {
    return academicSubjects;
  }

  public void setAcademicSubjects(List<EdFiLearningStandardAcademicSubject> academicSubjects) {
    this.academicSubjects = academicSubjects;
  }

  public EdFiLearningStandard gradeLevels(List<EdFiLearningStandardGradeLevel> gradeLevels) {
    this.gradeLevels = gradeLevels;
    return this;
  }

  public EdFiLearningStandard addGradeLevelsItem(EdFiLearningStandardGradeLevel gradeLevelsItem) {
    this.gradeLevels.add(gradeLevelsItem);
    return this;
  }

   /**
   * An unordered collection of learningStandardGradeLevels. The grade levels for the specific learning standard.
   * @return gradeLevels
  **/
  @ApiModelProperty(example = "null", required = true, value = "An unordered collection of learningStandardGradeLevels. The grade levels for the specific learning standard.")
  public List<EdFiLearningStandardGradeLevel> getGradeLevels() {
    return gradeLevels;
  }

  public void setGradeLevels(List<EdFiLearningStandardGradeLevel> gradeLevels) {
    this.gradeLevels = gradeLevels;
  }

  public EdFiLearningStandard learningStandardId(String learningStandardId) {
    this.learningStandardId = learningStandardId;
    return this;
  }

   /**
   * The identifier for the specific learning standard (e.g., 111.15.3.1.A).
   * @return learningStandardId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier for the specific learning standard (e.g., 111.15.3.1.A).")
  public String getLearningStandardId() {
    return learningStandardId;
  }

  public void setLearningStandardId(String learningStandardId) {
    this.learningStandardId = learningStandardId;
  }

  public EdFiLearningStandard parentLearningStandardReference(EdFiLearningStandardReference parentLearningStandardReference) {
    this.parentLearningStandardReference = parentLearningStandardReference;
    return this;
  }

   /**
   * Get parentLearningStandardReference
   * @return parentLearningStandardReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiLearningStandardReference getParentLearningStandardReference() {
    return parentLearningStandardReference;
  }

  public void setParentLearningStandardReference(EdFiLearningStandardReference parentLearningStandardReference) {
    this.parentLearningStandardReference = parentLearningStandardReference;
  }

  public EdFiLearningStandard contentStandard(EdFiLearningStandardContentStandard contentStandard) {
    this.contentStandard = contentStandard;
    return this;
  }

   /**
   * Get contentStandard
   * @return contentStandard
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiLearningStandardContentStandard getContentStandard() {
    return contentStandard;
  }

  public void setContentStandard(EdFiLearningStandardContentStandard contentStandard) {
    this.contentStandard = contentStandard;
  }

  public EdFiLearningStandard courseTitle(String courseTitle) {
    this.courseTitle = courseTitle;
    return this;
  }

   /**
   * The official Course Title with which this learning standard is associated.
   * @return courseTitle
  **/
  @ApiModelProperty(example = "null", value = "The official Course Title with which this learning standard is associated.")
  public String getCourseTitle() {
    return courseTitle;
  }

  public void setCourseTitle(String courseTitle) {
    this.courseTitle = courseTitle;
  }

  public EdFiLearningStandard description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The text of the statement. The textual content that either describes a specific competency such as \"Apply the Pythagorean Theorem to determine unknown side lengths in right triangles in real-world and mathematical problems in two and three dimensions.\" or describes a less granular group of competencies within the taxonomy of the standards document, e.g. \"Understand and apply the Pythagorean Theorem,\" or \"Geometry\".
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = "The text of the statement. The textual content that either describes a specific competency such as \"Apply the Pythagorean Theorem to determine unknown side lengths in right triangles in real-world and mathematical problems in two and three dimensions.\" or describes a less granular group of competencies within the taxonomy of the standards document, e.g. \"Understand and apply the Pythagorean Theorem,\" or \"Geometry\".")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EdFiLearningStandard identificationCodes(List<EdFiLearningStandardIdentificationCode> identificationCodes) {
    this.identificationCodes = identificationCodes;
    return this;
  }

  public EdFiLearningStandard addIdentificationCodesItem(EdFiLearningStandardIdentificationCode identificationCodesItem) {
    this.identificationCodes.add(identificationCodesItem);
    return this;
  }

   /**
   * An unordered collection of learningStandardIdentificationCodes. A coding scheme that is used for identification and record-keeping purposes by schools, social services, or other agencies to refer to a learning standard.
   * @return identificationCodes
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of learningStandardIdentificationCodes. A coding scheme that is used for identification and record-keeping purposes by schools, social services, or other agencies to refer to a learning standard.")
  public List<EdFiLearningStandardIdentificationCode> getIdentificationCodes() {
    return identificationCodes;
  }

  public void setIdentificationCodes(List<EdFiLearningStandardIdentificationCode> identificationCodes) {
    this.identificationCodes = identificationCodes;
  }

  public EdFiLearningStandard learningStandardCategoryDescriptor(String learningStandardCategoryDescriptor) {
    this.learningStandardCategoryDescriptor = learningStandardCategoryDescriptor;
    return this;
  }

   /**
   * An additional classification of the type of a specific learning standard.
   * @return learningStandardCategoryDescriptor
  **/
  @ApiModelProperty(example = "null", value = "An additional classification of the type of a specific learning standard.")
  public String getLearningStandardCategoryDescriptor() {
    return learningStandardCategoryDescriptor;
  }

  public void setLearningStandardCategoryDescriptor(String learningStandardCategoryDescriptor) {
    this.learningStandardCategoryDescriptor = learningStandardCategoryDescriptor;
  }

  public EdFiLearningStandard learningStandardItemCode(String learningStandardItemCode) {
    this.learningStandardItemCode = learningStandardItemCode;
    return this;
  }

   /**
   * A code designated by the promulgating body to identify the statement, e.g. 1.N.3 (usually not globally unique).
   * @return learningStandardItemCode
  **/
  @ApiModelProperty(example = "null", value = "A code designated by the promulgating body to identify the statement, e.g. 1.N.3 (usually not globally unique).")
  public String getLearningStandardItemCode() {
    return learningStandardItemCode;
  }

  public void setLearningStandardItemCode(String learningStandardItemCode) {
    this.learningStandardItemCode = learningStandardItemCode;
  }

  public EdFiLearningStandard namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * Namespace for the LearningStandard.
   * @return namespace
  **/
  @ApiModelProperty(example = "null", required = true, value = "Namespace for the LearningStandard.")
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public EdFiLearningStandard prerequisiteLearningStandards(List<EdFiLearningStandardPrerequisiteLearningStandard> prerequisiteLearningStandards) {
    this.prerequisiteLearningStandards = prerequisiteLearningStandards;
    return this;
  }

  public EdFiLearningStandard addPrerequisiteLearningStandardsItem(EdFiLearningStandardPrerequisiteLearningStandard prerequisiteLearningStandardsItem) {
    this.prerequisiteLearningStandards.add(prerequisiteLearningStandardsItem);
    return this;
  }

   /**
   * An unordered collection of learningStandardPrerequisiteLearningStandards. The unique identifier of a prerequisite learning standard item, a competency needed prior to learning this one. (Some items may have no prerequisites others may have one or more prerequisites. This should only be used to represent the immediate predecessors in a competency-based pathway, i.e. not prerequisites of prerequisites).
   * @return prerequisiteLearningStandards
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of learningStandardPrerequisiteLearningStandards. The unique identifier of a prerequisite learning standard item, a competency needed prior to learning this one. (Some items may have no prerequisites others may have one or more prerequisites. This should only be used to represent the immediate predecessors in a competency-based pathway, i.e. not prerequisites of prerequisites).")
  public List<EdFiLearningStandardPrerequisiteLearningStandard> getPrerequisiteLearningStandards() {
    return prerequisiteLearningStandards;
  }

  public void setPrerequisiteLearningStandards(List<EdFiLearningStandardPrerequisiteLearningStandard> prerequisiteLearningStandards) {
    this.prerequisiteLearningStandards = prerequisiteLearningStandards;
  }

  public EdFiLearningStandard successCriteria(String successCriteria) {
    this.successCriteria = successCriteria;
    return this;
  }

   /**
   * One or more statements that describes the criteria used by teachers and students to check for attainment of a learning standard. This criteria gives clear indications as to the degree to which learning is moving through the Zone or Proximal Development toward independent achievement of the LearningStandard.
   * @return successCriteria
  **/
  @ApiModelProperty(example = "null", value = "One or more statements that describes the criteria used by teachers and students to check for attainment of a learning standard. This criteria gives clear indications as to the degree to which learning is moving through the Zone or Proximal Development toward independent achievement of the LearningStandard.")
  public String getSuccessCriteria() {
    return successCriteria;
  }

  public void setSuccessCriteria(String successCriteria) {
    this.successCriteria = successCriteria;
  }

  public EdFiLearningStandard uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * An unambiguous reference to the statement using a network-resolvable URI.
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "An unambiguous reference to the statement using a network-resolvable URI.")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public EdFiLearningStandard etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiLearningStandard edFiLearningStandard = (EdFiLearningStandard) o;
    return Objects.equals(this.id, edFiLearningStandard.id) &&
        Objects.equals(this.academicSubjects, edFiLearningStandard.academicSubjects) &&
        Objects.equals(this.gradeLevels, edFiLearningStandard.gradeLevels) &&
        Objects.equals(this.learningStandardId, edFiLearningStandard.learningStandardId) &&
        Objects.equals(this.parentLearningStandardReference, edFiLearningStandard.parentLearningStandardReference) &&
        Objects.equals(this.contentStandard, edFiLearningStandard.contentStandard) &&
        Objects.equals(this.courseTitle, edFiLearningStandard.courseTitle) &&
        Objects.equals(this.description, edFiLearningStandard.description) &&
        Objects.equals(this.identificationCodes, edFiLearningStandard.identificationCodes) &&
        Objects.equals(this.learningStandardCategoryDescriptor, edFiLearningStandard.learningStandardCategoryDescriptor) &&
        Objects.equals(this.learningStandardItemCode, edFiLearningStandard.learningStandardItemCode) &&
        Objects.equals(this.namespace, edFiLearningStandard.namespace) &&
        Objects.equals(this.prerequisiteLearningStandards, edFiLearningStandard.prerequisiteLearningStandards) &&
        Objects.equals(this.successCriteria, edFiLearningStandard.successCriteria) &&
        Objects.equals(this.uri, edFiLearningStandard.uri) &&
        Objects.equals(this.etag, edFiLearningStandard.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, academicSubjects, gradeLevels, learningStandardId, parentLearningStandardReference, contentStandard, courseTitle, description, identificationCodes, learningStandardCategoryDescriptor, learningStandardItemCode, namespace, prerequisiteLearningStandards, successCriteria, uri, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiLearningStandard {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    academicSubjects: ").append(toIndentedString(academicSubjects)).append("\n");
    sb.append("    gradeLevels: ").append(toIndentedString(gradeLevels)).append("\n");
    sb.append("    learningStandardId: ").append(toIndentedString(learningStandardId)).append("\n");
    sb.append("    parentLearningStandardReference: ").append(toIndentedString(parentLearningStandardReference)).append("\n");
    sb.append("    contentStandard: ").append(toIndentedString(contentStandard)).append("\n");
    sb.append("    courseTitle: ").append(toIndentedString(courseTitle)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    identificationCodes: ").append(toIndentedString(identificationCodes)).append("\n");
    sb.append("    learningStandardCategoryDescriptor: ").append(toIndentedString(learningStandardCategoryDescriptor)).append("\n");
    sb.append("    learningStandardItemCode: ").append(toIndentedString(learningStandardItemCode)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    prerequisiteLearningStandards: ").append(toIndentedString(prerequisiteLearningStandards)).append("\n");
    sb.append("    successCriteria: ").append(toIndentedString(successCriteria)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

