/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.edfi.model.resource.EdFiEducationOrganizationReference;


/**
 * EdFiAccountCode
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class EdFiAccountCode   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("accountClassificationDescriptor")
  private String accountClassificationDescriptor = null;

  @SerializedName("accountCodeNumber")
  private String accountCodeNumber = null;

  @SerializedName("fiscalYear")
  private Integer fiscalYear = null;

  @SerializedName("educationOrganizationReference")
  private EdFiEducationOrganizationReference educationOrganizationReference = null;

  @SerializedName("accountCodeDescription")
  private String accountCodeDescription = null;

  @SerializedName("_etag")
  private String etag = null;

  public EdFiAccountCode id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EdFiAccountCode accountClassificationDescriptor(String accountClassificationDescriptor) {
    this.accountClassificationDescriptor = accountClassificationDescriptor;
    return this;
  }

   /**
   * The type of account code associated with the account.
   * @return accountClassificationDescriptor
  **/
  @ApiModelProperty(example = "null", required = true, value = "The type of account code associated with the account.")
  public String getAccountClassificationDescriptor() {
    return accountClassificationDescriptor;
  }

  public void setAccountClassificationDescriptor(String accountClassificationDescriptor) {
    this.accountClassificationDescriptor = accountClassificationDescriptor;
  }

  public EdFiAccountCode accountCodeNumber(String accountCodeNumber) {
    this.accountCodeNumber = accountCodeNumber;
    return this;
  }

   /**
   * An account code defined for the education accounting system by the education organization.
   * @return accountCodeNumber
  **/
  @ApiModelProperty(example = "null", required = true, value = "An account code defined for the education accounting system by the education organization.")
  public String getAccountCodeNumber() {
    return accountCodeNumber;
  }

  public void setAccountCodeNumber(String accountCodeNumber) {
    this.accountCodeNumber = accountCodeNumber;
  }

  public EdFiAccountCode fiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
    return this;
  }

   /**
   * The financial accounting year.
   * @return fiscalYear
  **/
  @ApiModelProperty(example = "null", required = true, value = "The financial accounting year.")
  public Integer getFiscalYear() {
    return fiscalYear;
  }

  public void setFiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
  }

  public EdFiAccountCode educationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
    return this;
  }

   /**
   * Get educationOrganizationReference
   * @return educationOrganizationReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiEducationOrganizationReference getEducationOrganizationReference() {
    return educationOrganizationReference;
  }

  public void setEducationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
  }

  public EdFiAccountCode accountCodeDescription(String accountCodeDescription) {
    this.accountCodeDescription = accountCodeDescription;
    return this;
  }

   /**
   * A description of the account code.
   * @return accountCodeDescription
  **/
  @ApiModelProperty(example = "null", value = "A description of the account code.")
  public String getAccountCodeDescription() {
    return accountCodeDescription;
  }

  public void setAccountCodeDescription(String accountCodeDescription) {
    this.accountCodeDescription = accountCodeDescription;
  }

  public EdFiAccountCode etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiAccountCode edFiAccountCode = (EdFiAccountCode) o;
    return Objects.equals(this.id, edFiAccountCode.id) &&
        Objects.equals(this.accountClassificationDescriptor, edFiAccountCode.accountClassificationDescriptor) &&
        Objects.equals(this.accountCodeNumber, edFiAccountCode.accountCodeNumber) &&
        Objects.equals(this.fiscalYear, edFiAccountCode.fiscalYear) &&
        Objects.equals(this.educationOrganizationReference, edFiAccountCode.educationOrganizationReference) &&
        Objects.equals(this.accountCodeDescription, edFiAccountCode.accountCodeDescription) &&
        Objects.equals(this.etag, edFiAccountCode.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountClassificationDescriptor, accountCodeNumber, fiscalYear, educationOrganizationReference, accountCodeDescription, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiAccountCode {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountClassificationDescriptor: ").append(toIndentedString(accountClassificationDescriptor)).append("\n");
    sb.append("    accountCodeNumber: ").append(toIndentedString(accountCodeNumber)).append("\n");
    sb.append("    fiscalYear: ").append(toIndentedString(fiscalYear)).append("\n");
    sb.append("    educationOrganizationReference: ").append(toIndentedString(educationOrganizationReference)).append("\n");
    sb.append("    accountCodeDescription: ").append(toIndentedString(accountCodeDescription)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

