/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.edfi.model.resource.EdFiEducationOrganizationReference;
import org.edfi.model.resource.EdFiSchoolYearTypeReference;
import org.edfi.model.resource.TpdmAnonymizedStudentReference;
import org.joda.time.LocalDate;


/**
 * TpdmAnonymizedStudentAcademicRecord
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmAnonymizedStudentAcademicRecord   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("factAsOfDate")
  private LocalDate factAsOfDate = null;

  @SerializedName("termDescriptor")
  private String termDescriptor = null;

  @SerializedName("anonymizedStudentReference")
  private TpdmAnonymizedStudentReference anonymizedStudentReference = null;

  @SerializedName("educationOrganizationReference")
  private EdFiEducationOrganizationReference educationOrganizationReference = null;

  @SerializedName("schoolYearTypeReference")
  private EdFiSchoolYearTypeReference schoolYearTypeReference = null;

  @SerializedName("cumulativeGradePointAverage")
  private Double cumulativeGradePointAverage = null;

  @SerializedName("gpaMax")
  private Double gpaMax = null;

  @SerializedName("sessionGradePointAverage")
  private Double sessionGradePointAverage = null;

  @SerializedName("_etag")
  private String etag = null;

  public TpdmAnonymizedStudentAcademicRecord id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TpdmAnonymizedStudentAcademicRecord factAsOfDate(LocalDate factAsOfDate) {
    this.factAsOfDate = factAsOfDate;
    return this;
  }

   /**
   * The date for which the data element is relevant
   * @return factAsOfDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "The date for which the data element is relevant")
  public LocalDate getFactAsOfDate() {
    return factAsOfDate;
  }

  public void setFactAsOfDate(LocalDate factAsOfDate) {
    this.factAsOfDate = factAsOfDate;
  }

  public TpdmAnonymizedStudentAcademicRecord termDescriptor(String termDescriptor) {
    this.termDescriptor = termDescriptor;
    return this;
  }

   /**
   * The term for the session during the school year.
   * @return termDescriptor
  **/
  @ApiModelProperty(example = "null", required = true, value = "The term for the session during the school year.")
  public String getTermDescriptor() {
    return termDescriptor;
  }

  public void setTermDescriptor(String termDescriptor) {
    this.termDescriptor = termDescriptor;
  }

  public TpdmAnonymizedStudentAcademicRecord anonymizedStudentReference(TpdmAnonymizedStudentReference anonymizedStudentReference) {
    this.anonymizedStudentReference = anonymizedStudentReference;
    return this;
  }

   /**
   * Get anonymizedStudentReference
   * @return anonymizedStudentReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TpdmAnonymizedStudentReference getAnonymizedStudentReference() {
    return anonymizedStudentReference;
  }

  public void setAnonymizedStudentReference(TpdmAnonymizedStudentReference anonymizedStudentReference) {
    this.anonymizedStudentReference = anonymizedStudentReference;
  }

  public TpdmAnonymizedStudentAcademicRecord educationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
    return this;
  }

   /**
   * Get educationOrganizationReference
   * @return educationOrganizationReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiEducationOrganizationReference getEducationOrganizationReference() {
    return educationOrganizationReference;
  }

  public void setEducationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
  }

  public TpdmAnonymizedStudentAcademicRecord schoolYearTypeReference(EdFiSchoolYearTypeReference schoolYearTypeReference) {
    this.schoolYearTypeReference = schoolYearTypeReference;
    return this;
  }

   /**
   * Get schoolYearTypeReference
   * @return schoolYearTypeReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiSchoolYearTypeReference getSchoolYearTypeReference() {
    return schoolYearTypeReference;
  }

  public void setSchoolYearTypeReference(EdFiSchoolYearTypeReference schoolYearTypeReference) {
    this.schoolYearTypeReference = schoolYearTypeReference;
  }

  public TpdmAnonymizedStudentAcademicRecord cumulativeGradePointAverage(Double cumulativeGradePointAverage) {
    this.cumulativeGradePointAverage = cumulativeGradePointAverage;
    return this;
  }

   /**
   * The average cumulative grade point average for a student
   * @return cumulativeGradePointAverage
  **/
  @ApiModelProperty(example = "null", value = "The average cumulative grade point average for a student")
  public Double getCumulativeGradePointAverage() {
    return cumulativeGradePointAverage;
  }

  public void setCumulativeGradePointAverage(Double cumulativeGradePointAverage) {
    this.cumulativeGradePointAverage = cumulativeGradePointAverage;
  }

  public TpdmAnonymizedStudentAcademicRecord gpaMax(Double gpaMax) {
    this.gpaMax = gpaMax;
    return this;
  }

   /**
   * The maximum grade point average that can be achieved by a student
   * @return gpaMax
  **/
  @ApiModelProperty(example = "null", value = "The maximum grade point average that can be achieved by a student")
  public Double getGpaMax() {
    return gpaMax;
  }

  public void setGpaMax(Double gpaMax) {
    this.gpaMax = gpaMax;
  }

  public TpdmAnonymizedStudentAcademicRecord sessionGradePointAverage(Double sessionGradePointAverage) {
    this.sessionGradePointAverage = sessionGradePointAverage;
    return this;
  }

   /**
   * The number of grade points an individual earned for this session.
   * @return sessionGradePointAverage
  **/
  @ApiModelProperty(example = "null", value = "The number of grade points an individual earned for this session.")
  public Double getSessionGradePointAverage() {
    return sessionGradePointAverage;
  }

  public void setSessionGradePointAverage(Double sessionGradePointAverage) {
    this.sessionGradePointAverage = sessionGradePointAverage;
  }

  public TpdmAnonymizedStudentAcademicRecord etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmAnonymizedStudentAcademicRecord tpdmAnonymizedStudentAcademicRecord = (TpdmAnonymizedStudentAcademicRecord) o;
    return Objects.equals(this.id, tpdmAnonymizedStudentAcademicRecord.id) &&
        Objects.equals(this.factAsOfDate, tpdmAnonymizedStudentAcademicRecord.factAsOfDate) &&
        Objects.equals(this.termDescriptor, tpdmAnonymizedStudentAcademicRecord.termDescriptor) &&
        Objects.equals(this.anonymizedStudentReference, tpdmAnonymizedStudentAcademicRecord.anonymizedStudentReference) &&
        Objects.equals(this.educationOrganizationReference, tpdmAnonymizedStudentAcademicRecord.educationOrganizationReference) &&
        Objects.equals(this.schoolYearTypeReference, tpdmAnonymizedStudentAcademicRecord.schoolYearTypeReference) &&
        Objects.equals(this.cumulativeGradePointAverage, tpdmAnonymizedStudentAcademicRecord.cumulativeGradePointAverage) &&
        Objects.equals(this.gpaMax, tpdmAnonymizedStudentAcademicRecord.gpaMax) &&
        Objects.equals(this.sessionGradePointAverage, tpdmAnonymizedStudentAcademicRecord.sessionGradePointAverage) &&
        Objects.equals(this.etag, tpdmAnonymizedStudentAcademicRecord.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, factAsOfDate, termDescriptor, anonymizedStudentReference, educationOrganizationReference, schoolYearTypeReference, cumulativeGradePointAverage, gpaMax, sessionGradePointAverage, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmAnonymizedStudentAcademicRecord {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    factAsOfDate: ").append(toIndentedString(factAsOfDate)).append("\n");
    sb.append("    termDescriptor: ").append(toIndentedString(termDescriptor)).append("\n");
    sb.append("    anonymizedStudentReference: ").append(toIndentedString(anonymizedStudentReference)).append("\n");
    sb.append("    educationOrganizationReference: ").append(toIndentedString(educationOrganizationReference)).append("\n");
    sb.append("    schoolYearTypeReference: ").append(toIndentedString(schoolYearTypeReference)).append("\n");
    sb.append("    cumulativeGradePointAverage: ").append(toIndentedString(cumulativeGradePointAverage)).append("\n");
    sb.append("    gpaMax: ").append(toIndentedString(gpaMax)).append("\n");
    sb.append("    sessionGradePointAverage: ").append(toIndentedString(sessionGradePointAverage)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

