/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.TpdmStaffBackgroundCheck;
import org.edfi.model.resource.TpdmStaffHighlyQualifiedAcademicSubject;
import org.edfi.model.resource.TpdmStaffSalary;
import org.edfi.model.resource.TpdmStaffSeniority;
import org.edfi.model.resource.TpdmStaffTeacherEducatorResearch;
import org.edfi.model.resource.TpdmStaffTeacherPreparationProgram;
import org.joda.time.LocalDate;


/**
 * TpdmStaffExtension
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmStaffExtension   {
  @SerializedName("genderDescriptor")
  private String genderDescriptor = null;

  @SerializedName("probationCompleteDate")
  private LocalDate probationCompleteDate = null;

  @SerializedName("tenured")
  private Boolean tenured = null;

  @SerializedName("tenureTrack")
  private Boolean tenureTrack = null;

  @SerializedName("backgroundChecks")
  private List<TpdmStaffBackgroundCheck> backgroundChecks = new ArrayList<TpdmStaffBackgroundCheck>();

  @SerializedName("highlyQualifiedAcademicSubjects")
  private List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects = new ArrayList<TpdmStaffHighlyQualifiedAcademicSubject>();

  @SerializedName("seniorities")
  private List<TpdmStaffSeniority> seniorities = new ArrayList<TpdmStaffSeniority>();

  @SerializedName("teacherPreparationPrograms")
  private List<TpdmStaffTeacherPreparationProgram> teacherPreparationPrograms = new ArrayList<TpdmStaffTeacherPreparationProgram>();

  @SerializedName("salary")
  private TpdmStaffSalary salary = null;

  @SerializedName("teacherEducatorResearch")
  private TpdmStaffTeacherEducatorResearch teacherEducatorResearch = null;

  public TpdmStaffExtension genderDescriptor(String genderDescriptor) {
    this.genderDescriptor = genderDescriptor;
    return this;
  }

   /**
   * The gender with which a person associates.
   * @return genderDescriptor
  **/
  @ApiModelProperty(example = "null", value = "The gender with which a person associates.")
  public String getGenderDescriptor() {
    return genderDescriptor;
  }

  public void setGenderDescriptor(String genderDescriptor) {
    this.genderDescriptor = genderDescriptor;
  }

  public TpdmStaffExtension probationCompleteDate(LocalDate probationCompleteDate) {
    this.probationCompleteDate = probationCompleteDate;
    return this;
  }

   /**
   * The date the probation period ended or is scheduled to end.
   * @return probationCompleteDate
  **/
  @ApiModelProperty(example = "null", value = "The date the probation period ended or is scheduled to end.")
  public LocalDate getProbationCompleteDate() {
    return probationCompleteDate;
  }

  public void setProbationCompleteDate(LocalDate probationCompleteDate) {
    this.probationCompleteDate = probationCompleteDate;
  }

  public TpdmStaffExtension tenured(Boolean tenured) {
    this.tenured = tenured;
    return this;
  }

   /**
   * Indicator of whether the staff member is tenured.
   * @return tenured
  **/
  @ApiModelProperty(example = "null", value = "Indicator of whether the staff member is tenured.")
  public Boolean getTenured() {
    return tenured;
  }

  public void setTenured(Boolean tenured) {
    this.tenured = tenured;
  }

  public TpdmStaffExtension tenureTrack(Boolean tenureTrack) {
    this.tenureTrack = tenureTrack;
    return this;
  }

   /**
   * An indication that the staff is on track for tenure.
   * @return tenureTrack
  **/
  @ApiModelProperty(example = "null", value = "An indication that the staff is on track for tenure.")
  public Boolean getTenureTrack() {
    return tenureTrack;
  }

  public void setTenureTrack(Boolean tenureTrack) {
    this.tenureTrack = tenureTrack;
  }

  public TpdmStaffExtension backgroundChecks(List<TpdmStaffBackgroundCheck> backgroundChecks) {
    this.backgroundChecks = backgroundChecks;
    return this;
  }

  public TpdmStaffExtension addBackgroundChecksItem(TpdmStaffBackgroundCheck backgroundChecksItem) {
    this.backgroundChecks.add(backgroundChecksItem);
    return this;
  }

   /**
   * An unordered collection of staffBackgroundChecks. Staff background check history and disposition.
   * @return backgroundChecks
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of staffBackgroundChecks. Staff background check history and disposition.")
  public List<TpdmStaffBackgroundCheck> getBackgroundChecks() {
    return backgroundChecks;
  }

  public void setBackgroundChecks(List<TpdmStaffBackgroundCheck> backgroundChecks) {
    this.backgroundChecks = backgroundChecks;
  }

  public TpdmStaffExtension highlyQualifiedAcademicSubjects(List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects) {
    this.highlyQualifiedAcademicSubjects = highlyQualifiedAcademicSubjects;
    return this;
  }

  public TpdmStaffExtension addHighlyQualifiedAcademicSubjectsItem(TpdmStaffHighlyQualifiedAcademicSubject highlyQualifiedAcademicSubjectsItem) {
    this.highlyQualifiedAcademicSubjects.add(highlyQualifiedAcademicSubjectsItem);
    return this;
  }

   /**
   * An unordered collection of staffHighlyQualifiedAcademicSubjects. The academic subject(s) in which the staff is deemed to be \"highly qualified\".
   * @return highlyQualifiedAcademicSubjects
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of staffHighlyQualifiedAcademicSubjects. The academic subject(s) in which the staff is deemed to be \"highly qualified\".")
  public List<TpdmStaffHighlyQualifiedAcademicSubject> getHighlyQualifiedAcademicSubjects() {
    return highlyQualifiedAcademicSubjects;
  }

  public void setHighlyQualifiedAcademicSubjects(List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects) {
    this.highlyQualifiedAcademicSubjects = highlyQualifiedAcademicSubjects;
  }

  public TpdmStaffExtension seniorities(List<TpdmStaffSeniority> seniorities) {
    this.seniorities = seniorities;
    return this;
  }

  public TpdmStaffExtension addSenioritiesItem(TpdmStaffSeniority senioritiesItem) {
    this.seniorities.add(senioritiesItem);
    return this;
  }

   /**
   * An unordered collection of staffSeniorities. Entries of job experience contributing to computations of seniority.
   * @return seniorities
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of staffSeniorities. Entries of job experience contributing to computations of seniority.")
  public List<TpdmStaffSeniority> getSeniorities() {
    return seniorities;
  }

  public void setSeniorities(List<TpdmStaffSeniority> seniorities) {
    this.seniorities = seniorities;
  }

  public TpdmStaffExtension teacherPreparationPrograms(List<TpdmStaffTeacherPreparationProgram> teacherPreparationPrograms) {
    this.teacherPreparationPrograms = teacherPreparationPrograms;
    return this;
  }

  public TpdmStaffExtension addTeacherPreparationProgramsItem(TpdmStaffTeacherPreparationProgram teacherPreparationProgramsItem) {
    this.teacherPreparationPrograms.add(teacherPreparationProgramsItem);
    return this;
  }

   /**
   * An unordered collection of staffTeacherPreparationPrograms. The Teacher Preparation Program(s) completed by the teacher.
   * @return teacherPreparationPrograms
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of staffTeacherPreparationPrograms. The Teacher Preparation Program(s) completed by the teacher.")
  public List<TpdmStaffTeacherPreparationProgram> getTeacherPreparationPrograms() {
    return teacherPreparationPrograms;
  }

  public void setTeacherPreparationPrograms(List<TpdmStaffTeacherPreparationProgram> teacherPreparationPrograms) {
    this.teacherPreparationPrograms = teacherPreparationPrograms;
  }

  public TpdmStaffExtension salary(TpdmStaffSalary salary) {
    this.salary = salary;
    return this;
  }

   /**
   * Get salary
   * @return salary
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmStaffSalary getSalary() {
    return salary;
  }

  public void setSalary(TpdmStaffSalary salary) {
    this.salary = salary;
  }

  public TpdmStaffExtension teacherEducatorResearch(TpdmStaffTeacherEducatorResearch teacherEducatorResearch) {
    this.teacherEducatorResearch = teacherEducatorResearch;
    return this;
  }

   /**
   * Get teacherEducatorResearch
   * @return teacherEducatorResearch
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmStaffTeacherEducatorResearch getTeacherEducatorResearch() {
    return teacherEducatorResearch;
  }

  public void setTeacherEducatorResearch(TpdmStaffTeacherEducatorResearch teacherEducatorResearch) {
    this.teacherEducatorResearch = teacherEducatorResearch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmStaffExtension tpdmStaffExtension = (TpdmStaffExtension) o;
    return Objects.equals(this.genderDescriptor, tpdmStaffExtension.genderDescriptor) &&
        Objects.equals(this.probationCompleteDate, tpdmStaffExtension.probationCompleteDate) &&
        Objects.equals(this.tenured, tpdmStaffExtension.tenured) &&
        Objects.equals(this.tenureTrack, tpdmStaffExtension.tenureTrack) &&
        Objects.equals(this.backgroundChecks, tpdmStaffExtension.backgroundChecks) &&
        Objects.equals(this.highlyQualifiedAcademicSubjects, tpdmStaffExtension.highlyQualifiedAcademicSubjects) &&
        Objects.equals(this.seniorities, tpdmStaffExtension.seniorities) &&
        Objects.equals(this.teacherPreparationPrograms, tpdmStaffExtension.teacherPreparationPrograms) &&
        Objects.equals(this.salary, tpdmStaffExtension.salary) &&
        Objects.equals(this.teacherEducatorResearch, tpdmStaffExtension.teacherEducatorResearch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genderDescriptor, probationCompleteDate, tenured, tenureTrack, backgroundChecks, highlyQualifiedAcademicSubjects, seniorities, teacherPreparationPrograms, salary, teacherEducatorResearch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmStaffExtension {\n");
    
    sb.append("    genderDescriptor: ").append(toIndentedString(genderDescriptor)).append("\n");
    sb.append("    probationCompleteDate: ").append(toIndentedString(probationCompleteDate)).append("\n");
    sb.append("    tenured: ").append(toIndentedString(tenured)).append("\n");
    sb.append("    tenureTrack: ").append(toIndentedString(tenureTrack)).append("\n");
    sb.append("    backgroundChecks: ").append(toIndentedString(backgroundChecks)).append("\n");
    sb.append("    highlyQualifiedAcademicSubjects: ").append(toIndentedString(highlyQualifiedAcademicSubjects)).append("\n");
    sb.append("    seniorities: ").append(toIndentedString(seniorities)).append("\n");
    sb.append("    teacherPreparationPrograms: ").append(toIndentedString(teacherPreparationPrograms)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("    teacherEducatorResearch: ").append(toIndentedString(teacherEducatorResearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

