/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.EdFiCourseReference;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedByDisability;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedDisabilityTotalStudentsDisabled;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedELLEnrollment;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedESLEnrollment;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedGender;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedLanguage;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedRace;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedSPED;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedSection504Enrollment;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedSex;
import org.edfi.model.resource.TpdmCourseStudentFactsAggregatedTitleIEnrollment;
import org.edfi.model.resource.TpdmCourseStudentFactsStudentsEnrolled;
import org.joda.time.LocalDate;


/**
 * TpdmCourseStudentFacts
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmCourseStudentFacts   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("factAsOfDate")
  private LocalDate factAsOfDate = null;

  @SerializedName("courseReference")
  private EdFiCourseReference courseReference = null;

  @SerializedName("aggregatedByDisabilities")
  private List<TpdmCourseStudentFactsAggregatedByDisability> aggregatedByDisabilities = new ArrayList<TpdmCourseStudentFactsAggregatedByDisability>();

  @SerializedName("aggregatedDisabilityTotalStudentsDisabled")
  private TpdmCourseStudentFactsAggregatedDisabilityTotalStudentsDisabled aggregatedDisabilityTotalStudentsDisabled = null;

  @SerializedName("aggregatedELLEnrollment")
  private TpdmCourseStudentFactsAggregatedELLEnrollment aggregatedELLEnrollment = null;

  @SerializedName("aggregatedESLEnrollment")
  private TpdmCourseStudentFactsAggregatedESLEnrollment aggregatedESLEnrollment = null;

  @SerializedName("aggregatedGenders")
  private List<TpdmCourseStudentFactsAggregatedGender> aggregatedGenders = new ArrayList<TpdmCourseStudentFactsAggregatedGender>();

  @SerializedName("aggregatedHispanicLatinoEthnicities")
  private List<TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity> aggregatedHispanicLatinoEthnicities = new ArrayList<TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity>();

  @SerializedName("aggregatedLanguages")
  private List<TpdmCourseStudentFactsAggregatedLanguage> aggregatedLanguages = new ArrayList<TpdmCourseStudentFactsAggregatedLanguage>();

  @SerializedName("aggregatedRaces")
  private List<TpdmCourseStudentFactsAggregatedRace> aggregatedRaces = new ArrayList<TpdmCourseStudentFactsAggregatedRace>();

  @SerializedName("aggregatedSchoolFoodServiceProgramServices")
  private List<TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService> aggregatedSchoolFoodServiceProgramServices = new ArrayList<TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService>();

  @SerializedName("aggregatedSection504Enrollment")
  private TpdmCourseStudentFactsAggregatedSection504Enrollment aggregatedSection504Enrollment = null;

  @SerializedName("aggregatedSexes")
  private List<TpdmCourseStudentFactsAggregatedSex> aggregatedSexes = new ArrayList<TpdmCourseStudentFactsAggregatedSex>();

  @SerializedName("aggregatedSPED")
  private TpdmCourseStudentFactsAggregatedSPED aggregatedSPED = null;

  @SerializedName("aggregatedTitleIEnrollment")
  private TpdmCourseStudentFactsAggregatedTitleIEnrollment aggregatedTitleIEnrollment = null;

  @SerializedName("studentsEnrolled")
  private TpdmCourseStudentFactsStudentsEnrolled studentsEnrolled = null;

  @SerializedName("_etag")
  private String etag = null;

  public TpdmCourseStudentFacts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TpdmCourseStudentFacts factAsOfDate(LocalDate factAsOfDate) {
    this.factAsOfDate = factAsOfDate;
    return this;
  }

   /**
   * The date for which the data element is relevant
   * @return factAsOfDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "The date for which the data element is relevant")
  public LocalDate getFactAsOfDate() {
    return factAsOfDate;
  }

  public void setFactAsOfDate(LocalDate factAsOfDate) {
    this.factAsOfDate = factAsOfDate;
  }

  public TpdmCourseStudentFacts courseReference(EdFiCourseReference courseReference) {
    this.courseReference = courseReference;
    return this;
  }

   /**
   * Get courseReference
   * @return courseReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiCourseReference getCourseReference() {
    return courseReference;
  }

  public void setCourseReference(EdFiCourseReference courseReference) {
    this.courseReference = courseReference;
  }

  public TpdmCourseStudentFacts aggregatedByDisabilities(List<TpdmCourseStudentFactsAggregatedByDisability> aggregatedByDisabilities) {
    this.aggregatedByDisabilities = aggregatedByDisabilities;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedByDisabilitiesItem(TpdmCourseStudentFactsAggregatedByDisability aggregatedByDisabilitiesItem) {
    this.aggregatedByDisabilities.add(aggregatedByDisabilitiesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedByDisabilities. Information about the disability of a group aggregated by course.
   * @return aggregatedByDisabilities
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedByDisabilities. Information about the disability of a group aggregated by course.")
  public List<TpdmCourseStudentFactsAggregatedByDisability> getAggregatedByDisabilities() {
    return aggregatedByDisabilities;
  }

  public void setAggregatedByDisabilities(List<TpdmCourseStudentFactsAggregatedByDisability> aggregatedByDisabilities) {
    this.aggregatedByDisabilities = aggregatedByDisabilities;
  }

  public TpdmCourseStudentFacts aggregatedDisabilityTotalStudentsDisabled(TpdmCourseStudentFactsAggregatedDisabilityTotalStudentsDisabled aggregatedDisabilityTotalStudentsDisabled) {
    this.aggregatedDisabilityTotalStudentsDisabled = aggregatedDisabilityTotalStudentsDisabled;
    return this;
  }

   /**
   * Get aggregatedDisabilityTotalStudentsDisabled
   * @return aggregatedDisabilityTotalStudentsDisabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedDisabilityTotalStudentsDisabled getAggregatedDisabilityTotalStudentsDisabled() {
    return aggregatedDisabilityTotalStudentsDisabled;
  }

  public void setAggregatedDisabilityTotalStudentsDisabled(TpdmCourseStudentFactsAggregatedDisabilityTotalStudentsDisabled aggregatedDisabilityTotalStudentsDisabled) {
    this.aggregatedDisabilityTotalStudentsDisabled = aggregatedDisabilityTotalStudentsDisabled;
  }

  public TpdmCourseStudentFacts aggregatedELLEnrollment(TpdmCourseStudentFactsAggregatedELLEnrollment aggregatedELLEnrollment) {
    this.aggregatedELLEnrollment = aggregatedELLEnrollment;
    return this;
  }

   /**
   * Get aggregatedELLEnrollment
   * @return aggregatedELLEnrollment
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedELLEnrollment getAggregatedELLEnrollment() {
    return aggregatedELLEnrollment;
  }

  public void setAggregatedELLEnrollment(TpdmCourseStudentFactsAggregatedELLEnrollment aggregatedELLEnrollment) {
    this.aggregatedELLEnrollment = aggregatedELLEnrollment;
  }

  public TpdmCourseStudentFacts aggregatedESLEnrollment(TpdmCourseStudentFactsAggregatedESLEnrollment aggregatedESLEnrollment) {
    this.aggregatedESLEnrollment = aggregatedESLEnrollment;
    return this;
  }

   /**
   * Get aggregatedESLEnrollment
   * @return aggregatedESLEnrollment
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedESLEnrollment getAggregatedESLEnrollment() {
    return aggregatedESLEnrollment;
  }

  public void setAggregatedESLEnrollment(TpdmCourseStudentFactsAggregatedESLEnrollment aggregatedESLEnrollment) {
    this.aggregatedESLEnrollment = aggregatedESLEnrollment;
  }

  public TpdmCourseStudentFacts aggregatedGenders(List<TpdmCourseStudentFactsAggregatedGender> aggregatedGenders) {
    this.aggregatedGenders = aggregatedGenders;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedGendersItem(TpdmCourseStudentFactsAggregatedGender aggregatedGendersItem) {
    this.aggregatedGenders.add(aggregatedGendersItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedGenders. The information about the gender
   * @return aggregatedGenders
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedGenders. The information about the gender")
  public List<TpdmCourseStudentFactsAggregatedGender> getAggregatedGenders() {
    return aggregatedGenders;
  }

  public void setAggregatedGenders(List<TpdmCourseStudentFactsAggregatedGender> aggregatedGenders) {
    this.aggregatedGenders = aggregatedGenders;
  }

  public TpdmCourseStudentFacts aggregatedHispanicLatinoEthnicities(List<TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity> aggregatedHispanicLatinoEthnicities) {
    this.aggregatedHispanicLatinoEthnicities = aggregatedHispanicLatinoEthnicities;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedHispanicLatinoEthnicitiesItem(TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity aggregatedHispanicLatinoEthnicitiesItem) {
    this.aggregatedHispanicLatinoEthnicities.add(aggregatedHispanicLatinoEthnicitiesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedHispanicLatinoEthnicities. Data about the Eth ethnicity of the group
   * @return aggregatedHispanicLatinoEthnicities
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedHispanicLatinoEthnicities. Data about the Eth ethnicity of the group")
  public List<TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity> getAggregatedHispanicLatinoEthnicities() {
    return aggregatedHispanicLatinoEthnicities;
  }

  public void setAggregatedHispanicLatinoEthnicities(List<TpdmCourseStudentFactsAggregatedHispanicLatinoEthnicity> aggregatedHispanicLatinoEthnicities) {
    this.aggregatedHispanicLatinoEthnicities = aggregatedHispanicLatinoEthnicities;
  }

  public TpdmCourseStudentFacts aggregatedLanguages(List<TpdmCourseStudentFactsAggregatedLanguage> aggregatedLanguages) {
    this.aggregatedLanguages = aggregatedLanguages;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedLanguagesItem(TpdmCourseStudentFactsAggregatedLanguage aggregatedLanguagesItem) {
    this.aggregatedLanguages.add(aggregatedLanguagesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedLanguages. The data about the language
   * @return aggregatedLanguages
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedLanguages. The data about the language")
  public List<TpdmCourseStudentFactsAggregatedLanguage> getAggregatedLanguages() {
    return aggregatedLanguages;
  }

  public void setAggregatedLanguages(List<TpdmCourseStudentFactsAggregatedLanguage> aggregatedLanguages) {
    this.aggregatedLanguages = aggregatedLanguages;
  }

  public TpdmCourseStudentFacts aggregatedRaces(List<TpdmCourseStudentFactsAggregatedRace> aggregatedRaces) {
    this.aggregatedRaces = aggregatedRaces;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedRacesItem(TpdmCourseStudentFactsAggregatedRace aggregatedRacesItem) {
    this.aggregatedRaces.add(aggregatedRacesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedRaces. Data about the race of the group
   * @return aggregatedRaces
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedRaces. Data about the race of the group")
  public List<TpdmCourseStudentFactsAggregatedRace> getAggregatedRaces() {
    return aggregatedRaces;
  }

  public void setAggregatedRaces(List<TpdmCourseStudentFactsAggregatedRace> aggregatedRaces) {
    this.aggregatedRaces = aggregatedRaces;
  }

  public TpdmCourseStudentFacts aggregatedSchoolFoodServiceProgramServices(List<TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService> aggregatedSchoolFoodServiceProgramServices) {
    this.aggregatedSchoolFoodServiceProgramServices = aggregatedSchoolFoodServiceProgramServices;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedSchoolFoodServiceProgramServicesItem(TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService aggregatedSchoolFoodServiceProgramServicesItem) {
    this.aggregatedSchoolFoodServiceProgramServices.add(aggregatedSchoolFoodServiceProgramServicesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedSchoolFoodServiceProgramServices. Identifies if the student is eligible for Free and Reduce Price Lunch
   * @return aggregatedSchoolFoodServiceProgramServices
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedSchoolFoodServiceProgramServices. Identifies if the student is eligible for Free and Reduce Price Lunch")
  public List<TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService> getAggregatedSchoolFoodServiceProgramServices() {
    return aggregatedSchoolFoodServiceProgramServices;
  }

  public void setAggregatedSchoolFoodServiceProgramServices(List<TpdmCourseStudentFactsAggregatedSchoolFoodServiceProgramService> aggregatedSchoolFoodServiceProgramServices) {
    this.aggregatedSchoolFoodServiceProgramServices = aggregatedSchoolFoodServiceProgramServices;
  }

  public TpdmCourseStudentFacts aggregatedSection504Enrollment(TpdmCourseStudentFactsAggregatedSection504Enrollment aggregatedSection504Enrollment) {
    this.aggregatedSection504Enrollment = aggregatedSection504Enrollment;
    return this;
  }

   /**
   * Get aggregatedSection504Enrollment
   * @return aggregatedSection504Enrollment
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedSection504Enrollment getAggregatedSection504Enrollment() {
    return aggregatedSection504Enrollment;
  }

  public void setAggregatedSection504Enrollment(TpdmCourseStudentFactsAggregatedSection504Enrollment aggregatedSection504Enrollment) {
    this.aggregatedSection504Enrollment = aggregatedSection504Enrollment;
  }

  public TpdmCourseStudentFacts aggregatedSexes(List<TpdmCourseStudentFactsAggregatedSex> aggregatedSexes) {
    this.aggregatedSexes = aggregatedSexes;
    return this;
  }

  public TpdmCourseStudentFacts addAggregatedSexesItem(TpdmCourseStudentFactsAggregatedSex aggregatedSexesItem) {
    this.aggregatedSexes.add(aggregatedSexesItem);
    return this;
  }

   /**
   * An unordered collection of courseStudentFactsAggregatedSexes. Data about the sex of the group
   * @return aggregatedSexes
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of courseStudentFactsAggregatedSexes. Data about the sex of the group")
  public List<TpdmCourseStudentFactsAggregatedSex> getAggregatedSexes() {
    return aggregatedSexes;
  }

  public void setAggregatedSexes(List<TpdmCourseStudentFactsAggregatedSex> aggregatedSexes) {
    this.aggregatedSexes = aggregatedSexes;
  }

  public TpdmCourseStudentFacts aggregatedSPED(TpdmCourseStudentFactsAggregatedSPED aggregatedSPED) {
    this.aggregatedSPED = aggregatedSPED;
    return this;
  }

   /**
   * Get aggregatedSPED
   * @return aggregatedSPED
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedSPED getAggregatedSPED() {
    return aggregatedSPED;
  }

  public void setAggregatedSPED(TpdmCourseStudentFactsAggregatedSPED aggregatedSPED) {
    this.aggregatedSPED = aggregatedSPED;
  }

  public TpdmCourseStudentFacts aggregatedTitleIEnrollment(TpdmCourseStudentFactsAggregatedTitleIEnrollment aggregatedTitleIEnrollment) {
    this.aggregatedTitleIEnrollment = aggregatedTitleIEnrollment;
    return this;
  }

   /**
   * Get aggregatedTitleIEnrollment
   * @return aggregatedTitleIEnrollment
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsAggregatedTitleIEnrollment getAggregatedTitleIEnrollment() {
    return aggregatedTitleIEnrollment;
  }

  public void setAggregatedTitleIEnrollment(TpdmCourseStudentFactsAggregatedTitleIEnrollment aggregatedTitleIEnrollment) {
    this.aggregatedTitleIEnrollment = aggregatedTitleIEnrollment;
  }

  public TpdmCourseStudentFacts studentsEnrolled(TpdmCourseStudentFactsStudentsEnrolled studentsEnrolled) {
    this.studentsEnrolled = studentsEnrolled;
    return this;
  }

   /**
   * Get studentsEnrolled
   * @return studentsEnrolled
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmCourseStudentFactsStudentsEnrolled getStudentsEnrolled() {
    return studentsEnrolled;
  }

  public void setStudentsEnrolled(TpdmCourseStudentFactsStudentsEnrolled studentsEnrolled) {
    this.studentsEnrolled = studentsEnrolled;
  }

  public TpdmCourseStudentFacts etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmCourseStudentFacts tpdmCourseStudentFacts = (TpdmCourseStudentFacts) o;
    return Objects.equals(this.id, tpdmCourseStudentFacts.id) &&
        Objects.equals(this.factAsOfDate, tpdmCourseStudentFacts.factAsOfDate) &&
        Objects.equals(this.courseReference, tpdmCourseStudentFacts.courseReference) &&
        Objects.equals(this.aggregatedByDisabilities, tpdmCourseStudentFacts.aggregatedByDisabilities) &&
        Objects.equals(this.aggregatedDisabilityTotalStudentsDisabled, tpdmCourseStudentFacts.aggregatedDisabilityTotalStudentsDisabled) &&
        Objects.equals(this.aggregatedELLEnrollment, tpdmCourseStudentFacts.aggregatedELLEnrollment) &&
        Objects.equals(this.aggregatedESLEnrollment, tpdmCourseStudentFacts.aggregatedESLEnrollment) &&
        Objects.equals(this.aggregatedGenders, tpdmCourseStudentFacts.aggregatedGenders) &&
        Objects.equals(this.aggregatedHispanicLatinoEthnicities, tpdmCourseStudentFacts.aggregatedHispanicLatinoEthnicities) &&
        Objects.equals(this.aggregatedLanguages, tpdmCourseStudentFacts.aggregatedLanguages) &&
        Objects.equals(this.aggregatedRaces, tpdmCourseStudentFacts.aggregatedRaces) &&
        Objects.equals(this.aggregatedSchoolFoodServiceProgramServices, tpdmCourseStudentFacts.aggregatedSchoolFoodServiceProgramServices) &&
        Objects.equals(this.aggregatedSection504Enrollment, tpdmCourseStudentFacts.aggregatedSection504Enrollment) &&
        Objects.equals(this.aggregatedSexes, tpdmCourseStudentFacts.aggregatedSexes) &&
        Objects.equals(this.aggregatedSPED, tpdmCourseStudentFacts.aggregatedSPED) &&
        Objects.equals(this.aggregatedTitleIEnrollment, tpdmCourseStudentFacts.aggregatedTitleIEnrollment) &&
        Objects.equals(this.studentsEnrolled, tpdmCourseStudentFacts.studentsEnrolled) &&
        Objects.equals(this.etag, tpdmCourseStudentFacts.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, factAsOfDate, courseReference, aggregatedByDisabilities, aggregatedDisabilityTotalStudentsDisabled, aggregatedELLEnrollment, aggregatedESLEnrollment, aggregatedGenders, aggregatedHispanicLatinoEthnicities, aggregatedLanguages, aggregatedRaces, aggregatedSchoolFoodServiceProgramServices, aggregatedSection504Enrollment, aggregatedSexes, aggregatedSPED, aggregatedTitleIEnrollment, studentsEnrolled, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmCourseStudentFacts {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    factAsOfDate: ").append(toIndentedString(factAsOfDate)).append("\n");
    sb.append("    courseReference: ").append(toIndentedString(courseReference)).append("\n");
    sb.append("    aggregatedByDisabilities: ").append(toIndentedString(aggregatedByDisabilities)).append("\n");
    sb.append("    aggregatedDisabilityTotalStudentsDisabled: ").append(toIndentedString(aggregatedDisabilityTotalStudentsDisabled)).append("\n");
    sb.append("    aggregatedELLEnrollment: ").append(toIndentedString(aggregatedELLEnrollment)).append("\n");
    sb.append("    aggregatedESLEnrollment: ").append(toIndentedString(aggregatedESLEnrollment)).append("\n");
    sb.append("    aggregatedGenders: ").append(toIndentedString(aggregatedGenders)).append("\n");
    sb.append("    aggregatedHispanicLatinoEthnicities: ").append(toIndentedString(aggregatedHispanicLatinoEthnicities)).append("\n");
    sb.append("    aggregatedLanguages: ").append(toIndentedString(aggregatedLanguages)).append("\n");
    sb.append("    aggregatedRaces: ").append(toIndentedString(aggregatedRaces)).append("\n");
    sb.append("    aggregatedSchoolFoodServiceProgramServices: ").append(toIndentedString(aggregatedSchoolFoodServiceProgramServices)).append("\n");
    sb.append("    aggregatedSection504Enrollment: ").append(toIndentedString(aggregatedSection504Enrollment)).append("\n");
    sb.append("    aggregatedSexes: ").append(toIndentedString(aggregatedSexes)).append("\n");
    sb.append("    aggregatedSPED: ").append(toIndentedString(aggregatedSPED)).append("\n");
    sb.append("    aggregatedTitleIEnrollment: ").append(toIndentedString(aggregatedTitleIEnrollment)).append("\n");
    sb.append("    studentsEnrolled: ").append(toIndentedString(studentsEnrolled)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

