/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.edfi.model.resource.EdFiSchoolYearTypeReference;
import org.edfi.model.resource.TpdmAnonymizedStudentAssessmentPerformanceLevel;
import org.edfi.model.resource.TpdmAnonymizedStudentAssessmentScoreResult;
import org.edfi.model.resource.TpdmAnonymizedStudentReference;
import org.joda.time.LocalDate;


/**
 * TpdmAnonymizedStudentAssessment
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmAnonymizedStudentAssessment   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("administrationDate")
  private LocalDate administrationDate = null;

  @SerializedName("assessmentIdentifier")
  private String assessmentIdentifier = null;

  @SerializedName("anonymizedStudentReference")
  private TpdmAnonymizedStudentReference anonymizedStudentReference = null;

  @SerializedName("takenSchoolYearTypeReference")
  private EdFiSchoolYearTypeReference takenSchoolYearTypeReference = null;

  @SerializedName("academicSubjectDescriptor")
  private String academicSubjectDescriptor = null;

  @SerializedName("assessmentCategoryDescriptor")
  private String assessmentCategoryDescriptor = null;

  @SerializedName("assessmentTitle")
  private String assessmentTitle = null;

  @SerializedName("gradeLevelDescriptor")
  private String gradeLevelDescriptor = null;

  @SerializedName("performanceLevel")
  private TpdmAnonymizedStudentAssessmentPerformanceLevel performanceLevel = null;

  @SerializedName("scoreResult")
  private TpdmAnonymizedStudentAssessmentScoreResult scoreResult = null;

  @SerializedName("termDescriptor")
  private String termDescriptor = null;

  @SerializedName("_etag")
  private String etag = null;

  public TpdmAnonymizedStudentAssessment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TpdmAnonymizedStudentAssessment administrationDate(LocalDate administrationDate) {
    this.administrationDate = administrationDate;
    return this;
  }

   /**
   * Date the assessment was administered
   * @return administrationDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "Date the assessment was administered")
  public LocalDate getAdministrationDate() {
    return administrationDate;
  }

  public void setAdministrationDate(LocalDate administrationDate) {
    this.administrationDate = administrationDate;
  }

  public TpdmAnonymizedStudentAssessment assessmentIdentifier(String assessmentIdentifier) {
    this.assessmentIdentifier = assessmentIdentifier;
    return this;
  }

   /**
   * An identifier that uniquely identifies the assessment to which the student results are associated.
   * @return assessmentIdentifier
  **/
  @ApiModelProperty(example = "null", required = true, value = "An identifier that uniquely identifies the assessment to which the student results are associated.")
  public String getAssessmentIdentifier() {
    return assessmentIdentifier;
  }

  public void setAssessmentIdentifier(String assessmentIdentifier) {
    this.assessmentIdentifier = assessmentIdentifier;
  }

  public TpdmAnonymizedStudentAssessment anonymizedStudentReference(TpdmAnonymizedStudentReference anonymizedStudentReference) {
    this.anonymizedStudentReference = anonymizedStudentReference;
    return this;
  }

   /**
   * Get anonymizedStudentReference
   * @return anonymizedStudentReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TpdmAnonymizedStudentReference getAnonymizedStudentReference() {
    return anonymizedStudentReference;
  }

  public void setAnonymizedStudentReference(TpdmAnonymizedStudentReference anonymizedStudentReference) {
    this.anonymizedStudentReference = anonymizedStudentReference;
  }

  public TpdmAnonymizedStudentAssessment takenSchoolYearTypeReference(EdFiSchoolYearTypeReference takenSchoolYearTypeReference) {
    this.takenSchoolYearTypeReference = takenSchoolYearTypeReference;
    return this;
  }

   /**
   * Get takenSchoolYearTypeReference
   * @return takenSchoolYearTypeReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiSchoolYearTypeReference getTakenSchoolYearTypeReference() {
    return takenSchoolYearTypeReference;
  }

  public void setTakenSchoolYearTypeReference(EdFiSchoolYearTypeReference takenSchoolYearTypeReference) {
    this.takenSchoolYearTypeReference = takenSchoolYearTypeReference;
  }

  public TpdmAnonymizedStudentAssessment academicSubjectDescriptor(String academicSubjectDescriptor) {
    this.academicSubjectDescriptor = academicSubjectDescriptor;
    return this;
  }

   /**
   * The academic subject associated with a student assessment
   * @return academicSubjectDescriptor
  **/
  @ApiModelProperty(example = "null", value = "The academic subject associated with a student assessment")
  public String getAcademicSubjectDescriptor() {
    return academicSubjectDescriptor;
  }

  public void setAcademicSubjectDescriptor(String academicSubjectDescriptor) {
    this.academicSubjectDescriptor = academicSubjectDescriptor;
  }

  public TpdmAnonymizedStudentAssessment assessmentCategoryDescriptor(String assessmentCategoryDescriptor) {
    this.assessmentCategoryDescriptor = assessmentCategoryDescriptor;
    return this;
  }

   /**
   * The category of an assessment based on format and content. For example: Achievement test Advanced placement test Alternate assessment/grade-level standards Attitudinal test Cognitive and perceptual skills test ...
   * @return assessmentCategoryDescriptor
  **/
  @ApiModelProperty(example = "null", value = "The category of an assessment based on format and content. For example: Achievement test Advanced placement test Alternate assessment/grade-level standards Attitudinal test Cognitive and perceptual skills test ...")
  public String getAssessmentCategoryDescriptor() {
    return assessmentCategoryDescriptor;
  }

  public void setAssessmentCategoryDescriptor(String assessmentCategoryDescriptor) {
    this.assessmentCategoryDescriptor = assessmentCategoryDescriptor;
  }

  public TpdmAnonymizedStudentAssessment assessmentTitle(String assessmentTitle) {
    this.assessmentTitle = assessmentTitle;
    return this;
  }

   /**
   * The title if any specific assessment given to a group
   * @return assessmentTitle
  **/
  @ApiModelProperty(example = "null", value = "The title if any specific assessment given to a group")
  public String getAssessmentTitle() {
    return assessmentTitle;
  }

  public void setAssessmentTitle(String assessmentTitle) {
    this.assessmentTitle = assessmentTitle;
  }

  public TpdmAnonymizedStudentAssessment gradeLevelDescriptor(String gradeLevelDescriptor) {
    this.gradeLevelDescriptor = gradeLevelDescriptor;
    return this;
  }

   /**
   * Grade level for which effectiveness is measured.
   * @return gradeLevelDescriptor
  **/
  @ApiModelProperty(example = "null", value = "Grade level for which effectiveness is measured.")
  public String getGradeLevelDescriptor() {
    return gradeLevelDescriptor;
  }

  public void setGradeLevelDescriptor(String gradeLevelDescriptor) {
    this.gradeLevelDescriptor = gradeLevelDescriptor;
  }

  public TpdmAnonymizedStudentAssessment performanceLevel(TpdmAnonymizedStudentAssessmentPerformanceLevel performanceLevel) {
    this.performanceLevel = performanceLevel;
    return this;
  }

   /**
   * Get performanceLevel
   * @return performanceLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmAnonymizedStudentAssessmentPerformanceLevel getPerformanceLevel() {
    return performanceLevel;
  }

  public void setPerformanceLevel(TpdmAnonymizedStudentAssessmentPerformanceLevel performanceLevel) {
    this.performanceLevel = performanceLevel;
  }

  public TpdmAnonymizedStudentAssessment scoreResult(TpdmAnonymizedStudentAssessmentScoreResult scoreResult) {
    this.scoreResult = scoreResult;
    return this;
  }

   /**
   * Get scoreResult
   * @return scoreResult
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmAnonymizedStudentAssessmentScoreResult getScoreResult() {
    return scoreResult;
  }

  public void setScoreResult(TpdmAnonymizedStudentAssessmentScoreResult scoreResult) {
    this.scoreResult = scoreResult;
  }

  public TpdmAnonymizedStudentAssessment termDescriptor(String termDescriptor) {
    this.termDescriptor = termDescriptor;
    return this;
  }

   /**
   * The term in which the assessment was administered
   * @return termDescriptor
  **/
  @ApiModelProperty(example = "null", value = "The term in which the assessment was administered")
  public String getTermDescriptor() {
    return termDescriptor;
  }

  public void setTermDescriptor(String termDescriptor) {
    this.termDescriptor = termDescriptor;
  }

  public TpdmAnonymizedStudentAssessment etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmAnonymizedStudentAssessment tpdmAnonymizedStudentAssessment = (TpdmAnonymizedStudentAssessment) o;
    return Objects.equals(this.id, tpdmAnonymizedStudentAssessment.id) &&
        Objects.equals(this.administrationDate, tpdmAnonymizedStudentAssessment.administrationDate) &&
        Objects.equals(this.assessmentIdentifier, tpdmAnonymizedStudentAssessment.assessmentIdentifier) &&
        Objects.equals(this.anonymizedStudentReference, tpdmAnonymizedStudentAssessment.anonymizedStudentReference) &&
        Objects.equals(this.takenSchoolYearTypeReference, tpdmAnonymizedStudentAssessment.takenSchoolYearTypeReference) &&
        Objects.equals(this.academicSubjectDescriptor, tpdmAnonymizedStudentAssessment.academicSubjectDescriptor) &&
        Objects.equals(this.assessmentCategoryDescriptor, tpdmAnonymizedStudentAssessment.assessmentCategoryDescriptor) &&
        Objects.equals(this.assessmentTitle, tpdmAnonymizedStudentAssessment.assessmentTitle) &&
        Objects.equals(this.gradeLevelDescriptor, tpdmAnonymizedStudentAssessment.gradeLevelDescriptor) &&
        Objects.equals(this.performanceLevel, tpdmAnonymizedStudentAssessment.performanceLevel) &&
        Objects.equals(this.scoreResult, tpdmAnonymizedStudentAssessment.scoreResult) &&
        Objects.equals(this.termDescriptor, tpdmAnonymizedStudentAssessment.termDescriptor) &&
        Objects.equals(this.etag, tpdmAnonymizedStudentAssessment.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, administrationDate, assessmentIdentifier, anonymizedStudentReference, takenSchoolYearTypeReference, academicSubjectDescriptor, assessmentCategoryDescriptor, assessmentTitle, gradeLevelDescriptor, performanceLevel, scoreResult, termDescriptor, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmAnonymizedStudentAssessment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    administrationDate: ").append(toIndentedString(administrationDate)).append("\n");
    sb.append("    assessmentIdentifier: ").append(toIndentedString(assessmentIdentifier)).append("\n");
    sb.append("    anonymizedStudentReference: ").append(toIndentedString(anonymizedStudentReference)).append("\n");
    sb.append("    takenSchoolYearTypeReference: ").append(toIndentedString(takenSchoolYearTypeReference)).append("\n");
    sb.append("    academicSubjectDescriptor: ").append(toIndentedString(academicSubjectDescriptor)).append("\n");
    sb.append("    assessmentCategoryDescriptor: ").append(toIndentedString(assessmentCategoryDescriptor)).append("\n");
    sb.append("    assessmentTitle: ").append(toIndentedString(assessmentTitle)).append("\n");
    sb.append("    gradeLevelDescriptor: ").append(toIndentedString(gradeLevelDescriptor)).append("\n");
    sb.append("    performanceLevel: ").append(toIndentedString(performanceLevel)).append("\n");
    sb.append("    scoreResult: ").append(toIndentedString(scoreResult)).append("\n");
    sb.append("    termDescriptor: ").append(toIndentedString(termDescriptor)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

