/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.edfi.model.resource.EdFiEducationOrganizationReference;
import org.edfi.model.resource.TpdmTeacherCandidateReference;
import org.edfi.model.resource.TpdmTeacherPreparationProviderProgramReference;
import org.joda.time.LocalDate;


/**
 * TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("beginDate")
  private LocalDate beginDate = null;

  @SerializedName("educationOrganizationReference")
  private EdFiEducationOrganizationReference educationOrganizationReference = null;

  @SerializedName("teacherCandidateReference")
  private TpdmTeacherCandidateReference teacherCandidateReference = null;

  @SerializedName("teacherPreparationProviderProgramReference")
  private TpdmTeacherPreparationProviderProgramReference teacherPreparationProviderProgramReference = null;

  @SerializedName("endDate")
  private LocalDate endDate = null;

  @SerializedName("reasonExitedDescriptor")
  private String reasonExitedDescriptor = null;

  @SerializedName("_etag")
  private String etag = null;

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation beginDate(LocalDate beginDate) {
    this.beginDate = beginDate;
    return this;
  }

   /**
   * The begin date for the association.
   * @return beginDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "The begin date for the association.")
  public LocalDate getBeginDate() {
    return beginDate;
  }

  public void setBeginDate(LocalDate beginDate) {
    this.beginDate = beginDate;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation educationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
    return this;
  }

   /**
   * Get educationOrganizationReference
   * @return educationOrganizationReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public EdFiEducationOrganizationReference getEducationOrganizationReference() {
    return educationOrganizationReference;
  }

  public void setEducationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation teacherCandidateReference(TpdmTeacherCandidateReference teacherCandidateReference) {
    this.teacherCandidateReference = teacherCandidateReference;
    return this;
  }

   /**
   * Get teacherCandidateReference
   * @return teacherCandidateReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TpdmTeacherCandidateReference getTeacherCandidateReference() {
    return teacherCandidateReference;
  }

  public void setTeacherCandidateReference(TpdmTeacherCandidateReference teacherCandidateReference) {
    this.teacherCandidateReference = teacherCandidateReference;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation teacherPreparationProviderProgramReference(TpdmTeacherPreparationProviderProgramReference teacherPreparationProviderProgramReference) {
    this.teacherPreparationProviderProgramReference = teacherPreparationProviderProgramReference;
    return this;
  }

   /**
   * Get teacherPreparationProviderProgramReference
   * @return teacherPreparationProviderProgramReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TpdmTeacherPreparationProviderProgramReference getTeacherPreparationProviderProgramReference() {
    return teacherPreparationProviderProgramReference;
  }

  public void setTeacherPreparationProviderProgramReference(TpdmTeacherPreparationProviderProgramReference teacherPreparationProviderProgramReference) {
    this.teacherPreparationProviderProgramReference = teacherPreparationProviderProgramReference;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * The end date for the association.
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "The end date for the association.")
  public LocalDate getEndDate() {
    return endDate;
  }

  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation reasonExitedDescriptor(String reasonExitedDescriptor) {
    this.reasonExitedDescriptor = reasonExitedDescriptor;
    return this;
  }

   /**
   * Reason exited for the association.
   * @return reasonExitedDescriptor
  **/
  @ApiModelProperty(example = "null", value = "Reason exited for the association.")
  public String getReasonExitedDescriptor() {
    return reasonExitedDescriptor;
  }

  public void setReasonExitedDescriptor(String reasonExitedDescriptor) {
    this.reasonExitedDescriptor = reasonExitedDescriptor;
  }

  public TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation = (TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation) o;
    return Objects.equals(this.id, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.id) &&
        Objects.equals(this.beginDate, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.beginDate) &&
        Objects.equals(this.educationOrganizationReference, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.educationOrganizationReference) &&
        Objects.equals(this.teacherCandidateReference, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.teacherCandidateReference) &&
        Objects.equals(this.teacherPreparationProviderProgramReference, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.teacherPreparationProviderProgramReference) &&
        Objects.equals(this.endDate, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.endDate) &&
        Objects.equals(this.reasonExitedDescriptor, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.reasonExitedDescriptor) &&
        Objects.equals(this.etag, tpdmTeacherCandidateTeacherPreparationProviderProgramAssociation.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, beginDate, educationOrganizationReference, teacherCandidateReference, teacherPreparationProviderProgramReference, endDate, reasonExitedDescriptor, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmTeacherCandidateTeacherPreparationProviderProgramAssociation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    educationOrganizationReference: ").append(toIndentedString(educationOrganizationReference)).append("\n");
    sb.append("    teacherCandidateReference: ").append(toIndentedString(teacherCandidateReference)).append("\n");
    sb.append("    teacherPreparationProviderProgramReference: ").append(toIndentedString(teacherPreparationProviderProgramReference)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    reasonExitedDescriptor: ").append(toIndentedString(reasonExitedDescriptor)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

