/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.edfi.model.resource.EdFiParentReference;
import org.edfi.model.resource.EdFiStaffReference;
import org.edfi.model.resource.EdFiStudentReference;
import org.edfi.model.resource.TpdmApplicantReference;
import org.edfi.model.resource.TpdmProspectReference;
import org.edfi.model.resource.TpdmSurveyReference;
import org.edfi.model.resource.TpdmSurveyResponseSurveyLevel;
import org.edfi.model.resource.TpdmTeacherCandidateReference;
import org.joda.time.LocalDate;


/**
 * TpdmSurveyResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmSurveyResponse   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("surveyResponseIdentifier")
  private String surveyResponseIdentifier = null;

  @SerializedName("applicantReference")
  private TpdmApplicantReference applicantReference = null;

  @SerializedName("parentReference")
  private EdFiParentReference parentReference = null;

  @SerializedName("prospectReference")
  private TpdmProspectReference prospectReference = null;

  @SerializedName("staffReference")
  private EdFiStaffReference staffReference = null;

  @SerializedName("studentReference")
  private EdFiStudentReference studentReference = null;

  @SerializedName("surveyReference")
  private TpdmSurveyReference surveyReference = null;

  @SerializedName("teacherCandidateReference")
  private TpdmTeacherCandidateReference teacherCandidateReference = null;

  @SerializedName("electronicMailAddress")
  private String electronicMailAddress = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("responseDate")
  private LocalDate responseDate = null;

  @SerializedName("responseTime")
  private Integer responseTime = null;

  @SerializedName("surveyLevels")
  private List<TpdmSurveyResponseSurveyLevel> surveyLevels = new ArrayList<TpdmSurveyResponseSurveyLevel>();

  @SerializedName("_etag")
  private String etag = null;

  public TpdmSurveyResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TpdmSurveyResponse surveyResponseIdentifier(String surveyResponseIdentifier) {
    this.surveyResponseIdentifier = surveyResponseIdentifier;
    return this;
  }

   /**
   * The identifier of the survey typically from the survey application.
   * @return surveyResponseIdentifier
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of the survey typically from the survey application.")
  public String getSurveyResponseIdentifier() {
    return surveyResponseIdentifier;
  }

  public void setSurveyResponseIdentifier(String surveyResponseIdentifier) {
    this.surveyResponseIdentifier = surveyResponseIdentifier;
  }

  public TpdmSurveyResponse applicantReference(TpdmApplicantReference applicantReference) {
    this.applicantReference = applicantReference;
    return this;
  }

   /**
   * Get applicantReference
   * @return applicantReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmApplicantReference getApplicantReference() {
    return applicantReference;
  }

  public void setApplicantReference(TpdmApplicantReference applicantReference) {
    this.applicantReference = applicantReference;
  }

  public TpdmSurveyResponse parentReference(EdFiParentReference parentReference) {
    this.parentReference = parentReference;
    return this;
  }

   /**
   * Get parentReference
   * @return parentReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiParentReference getParentReference() {
    return parentReference;
  }

  public void setParentReference(EdFiParentReference parentReference) {
    this.parentReference = parentReference;
  }

  public TpdmSurveyResponse prospectReference(TpdmProspectReference prospectReference) {
    this.prospectReference = prospectReference;
    return this;
  }

   /**
   * Get prospectReference
   * @return prospectReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmProspectReference getProspectReference() {
    return prospectReference;
  }

  public void setProspectReference(TpdmProspectReference prospectReference) {
    this.prospectReference = prospectReference;
  }

  public TpdmSurveyResponse staffReference(EdFiStaffReference staffReference) {
    this.staffReference = staffReference;
    return this;
  }

   /**
   * Get staffReference
   * @return staffReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiStaffReference getStaffReference() {
    return staffReference;
  }

  public void setStaffReference(EdFiStaffReference staffReference) {
    this.staffReference = staffReference;
  }

  public TpdmSurveyResponse studentReference(EdFiStudentReference studentReference) {
    this.studentReference = studentReference;
    return this;
  }

   /**
   * Get studentReference
   * @return studentReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public EdFiStudentReference getStudentReference() {
    return studentReference;
  }

  public void setStudentReference(EdFiStudentReference studentReference) {
    this.studentReference = studentReference;
  }

  public TpdmSurveyResponse surveyReference(TpdmSurveyReference surveyReference) {
    this.surveyReference = surveyReference;
    return this;
  }

   /**
   * Get surveyReference
   * @return surveyReference
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TpdmSurveyReference getSurveyReference() {
    return surveyReference;
  }

  public void setSurveyReference(TpdmSurveyReference surveyReference) {
    this.surveyReference = surveyReference;
  }

  public TpdmSurveyResponse teacherCandidateReference(TpdmTeacherCandidateReference teacherCandidateReference) {
    this.teacherCandidateReference = teacherCandidateReference;
    return this;
  }

   /**
   * Get teacherCandidateReference
   * @return teacherCandidateReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public TpdmTeacherCandidateReference getTeacherCandidateReference() {
    return teacherCandidateReference;
  }

  public void setTeacherCandidateReference(TpdmTeacherCandidateReference teacherCandidateReference) {
    this.teacherCandidateReference = teacherCandidateReference;
  }

  public TpdmSurveyResponse electronicMailAddress(String electronicMailAddress) {
    this.electronicMailAddress = electronicMailAddress;
    return this;
  }

   /**
   * Email address of the respondent.
   * @return electronicMailAddress
  **/
  @ApiModelProperty(example = "null", value = "Email address of the respondent.")
  public String getElectronicMailAddress() {
    return electronicMailAddress;
  }

  public void setElectronicMailAddress(String electronicMailAddress) {
    this.electronicMailAddress = electronicMailAddress;
  }

  public TpdmSurveyResponse fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Full name of the respondent.
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "Full name of the respondent.")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public TpdmSurveyResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Location of the respondent, often a city, district, or school.
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "Location of the respondent, often a city, district, or school.")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public TpdmSurveyResponse responseDate(LocalDate responseDate) {
    this.responseDate = responseDate;
    return this;
  }

   /**
   * Date of the survey response.
   * @return responseDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "Date of the survey response.")
  public LocalDate getResponseDate() {
    return responseDate;
  }

  public void setResponseDate(LocalDate responseDate) {
    this.responseDate = responseDate;
  }

  public TpdmSurveyResponse responseTime(Integer responseTime) {
    this.responseTime = responseTime;
    return this;
  }

   /**
   * The amount of time (in seconds) it took for the respondent to complete the survey.
   * @return responseTime
  **/
  @ApiModelProperty(example = "null", value = "The amount of time (in seconds) it took for the respondent to complete the survey.")
  public Integer getResponseTime() {
    return responseTime;
  }

  public void setResponseTime(Integer responseTime) {
    this.responseTime = responseTime;
  }

  public TpdmSurveyResponse surveyLevels(List<TpdmSurveyResponseSurveyLevel> surveyLevels) {
    this.surveyLevels = surveyLevels;
    return this;
  }

  public TpdmSurveyResponse addSurveyLevelsItem(TpdmSurveyResponseSurveyLevel surveyLevelsItem) {
    this.surveyLevels.add(surveyLevelsItem);
    return this;
  }

   /**
   * An unordered collection of surveyResponseSurveyLevels. Provides information about the respondents of a survey and how they can be grouped together (ex., grade level, grade band, course type, etc.).
   * @return surveyLevels
  **/
  @ApiModelProperty(example = "null", value = "An unordered collection of surveyResponseSurveyLevels. Provides information about the respondents of a survey and how they can be grouped together (ex., grade level, grade band, course type, etc.).")
  public List<TpdmSurveyResponseSurveyLevel> getSurveyLevels() {
    return surveyLevels;
  }

  public void setSurveyLevels(List<TpdmSurveyResponseSurveyLevel> surveyLevels) {
    this.surveyLevels = surveyLevels;
  }

  public TpdmSurveyResponse etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "A unique system-generated value that identifies the version of the resource.")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmSurveyResponse tpdmSurveyResponse = (TpdmSurveyResponse) o;
    return Objects.equals(this.id, tpdmSurveyResponse.id) &&
        Objects.equals(this.surveyResponseIdentifier, tpdmSurveyResponse.surveyResponseIdentifier) &&
        Objects.equals(this.applicantReference, tpdmSurveyResponse.applicantReference) &&
        Objects.equals(this.parentReference, tpdmSurveyResponse.parentReference) &&
        Objects.equals(this.prospectReference, tpdmSurveyResponse.prospectReference) &&
        Objects.equals(this.staffReference, tpdmSurveyResponse.staffReference) &&
        Objects.equals(this.studentReference, tpdmSurveyResponse.studentReference) &&
        Objects.equals(this.surveyReference, tpdmSurveyResponse.surveyReference) &&
        Objects.equals(this.teacherCandidateReference, tpdmSurveyResponse.teacherCandidateReference) &&
        Objects.equals(this.electronicMailAddress, tpdmSurveyResponse.electronicMailAddress) &&
        Objects.equals(this.fullName, tpdmSurveyResponse.fullName) &&
        Objects.equals(this.location, tpdmSurveyResponse.location) &&
        Objects.equals(this.responseDate, tpdmSurveyResponse.responseDate) &&
        Objects.equals(this.responseTime, tpdmSurveyResponse.responseTime) &&
        Objects.equals(this.surveyLevels, tpdmSurveyResponse.surveyLevels) &&
        Objects.equals(this.etag, tpdmSurveyResponse.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, surveyResponseIdentifier, applicantReference, parentReference, prospectReference, staffReference, studentReference, surveyReference, teacherCandidateReference, electronicMailAddress, fullName, location, responseDate, responseTime, surveyLevels, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmSurveyResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    surveyResponseIdentifier: ").append(toIndentedString(surveyResponseIdentifier)).append("\n");
    sb.append("    applicantReference: ").append(toIndentedString(applicantReference)).append("\n");
    sb.append("    parentReference: ").append(toIndentedString(parentReference)).append("\n");
    sb.append("    prospectReference: ").append(toIndentedString(prospectReference)).append("\n");
    sb.append("    staffReference: ").append(toIndentedString(staffReference)).append("\n");
    sb.append("    studentReference: ").append(toIndentedString(studentReference)).append("\n");
    sb.append("    surveyReference: ").append(toIndentedString(surveyReference)).append("\n");
    sb.append("    teacherCandidateReference: ").append(toIndentedString(teacherCandidateReference)).append("\n");
    sb.append("    electronicMailAddress: ").append(toIndentedString(electronicMailAddress)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    responseDate: ").append(toIndentedString(responseDate)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    surveyLevels: ").append(toIndentedString(surveyLevels)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

