/**
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface. The Ed-Fi ODS / API supports both transactional and bulk modes of operation.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.edfi.model.resource;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.edfi.model.resource.Link;
import org.joda.time.LocalDate;


/**
 * TpdmSectionSurveyResponseFactsReference
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-09T12:36:29.493-07:00")
public class TpdmSectionSurveyResponseFactsReference   {
  @SerializedName("factsAsOfDate")
  private LocalDate factsAsOfDate = null;

  @SerializedName("localCourseCode")
  private String localCourseCode = null;

  @SerializedName("schoolId")
  private Integer schoolId = null;

  @SerializedName("schoolYear")
  private Integer schoolYear = null;

  @SerializedName("sectionIdentifier")
  private String sectionIdentifier = null;

  @SerializedName("sessionName")
  private String sessionName = null;

  @SerializedName("surveyIdentifier")
  private String surveyIdentifier = null;

  @SerializedName("link")
  private Link link = null;

  public TpdmSectionSurveyResponseFactsReference factsAsOfDate(LocalDate factsAsOfDate) {
    this.factsAsOfDate = factsAsOfDate;
    return this;
  }

   /**
   * The as-of-date for the aggregated survey data.
   * @return factsAsOfDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "The as-of-date for the aggregated survey data.")
  public LocalDate getFactsAsOfDate() {
    return factsAsOfDate;
  }

  public void setFactsAsOfDate(LocalDate factsAsOfDate) {
    this.factsAsOfDate = factsAsOfDate;
  }

  public TpdmSectionSurveyResponseFactsReference localCourseCode(String localCourseCode) {
    this.localCourseCode = localCourseCode;
    return this;
  }

   /**
   * The local code assigned by the School that identifies the course offering provided for the instruction of students.
   * @return localCourseCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "The local code assigned by the School that identifies the course offering provided for the instruction of students.")
  public String getLocalCourseCode() {
    return localCourseCode;
  }

  public void setLocalCourseCode(String localCourseCode) {
    this.localCourseCode = localCourseCode;
  }

  public TpdmSectionSurveyResponseFactsReference schoolId(Integer schoolId) {
    this.schoolId = schoolId;
    return this;
  }

   /**
   * The identifier assigned to a school.
   * @return schoolId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier assigned to a school.")
  public Integer getSchoolId() {
    return schoolId;
  }

  public void setSchoolId(Integer schoolId) {
    this.schoolId = schoolId;
  }

  public TpdmSectionSurveyResponseFactsReference schoolYear(Integer schoolYear) {
    this.schoolYear = schoolYear;
    return this;
  }

   /**
   * The identifier for the school year.
   * @return schoolYear
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier for the school year.")
  public Integer getSchoolYear() {
    return schoolYear;
  }

  public void setSchoolYear(Integer schoolYear) {
    this.schoolYear = schoolYear;
  }

  public TpdmSectionSurveyResponseFactsReference sectionIdentifier(String sectionIdentifier) {
    this.sectionIdentifier = sectionIdentifier;
    return this;
  }

   /**
   * The local identifier assigned to a section.
   * @return sectionIdentifier
  **/
  @ApiModelProperty(example = "null", required = true, value = "The local identifier assigned to a section.")
  public String getSectionIdentifier() {
    return sectionIdentifier;
  }

  public void setSectionIdentifier(String sectionIdentifier) {
    this.sectionIdentifier = sectionIdentifier;
  }

  public TpdmSectionSurveyResponseFactsReference sessionName(String sessionName) {
    this.sessionName = sessionName;
    return this;
  }

   /**
   * The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).
   * @return sessionName
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).")
  public String getSessionName() {
    return sessionName;
  }

  public void setSessionName(String sessionName) {
    this.sessionName = sessionName;
  }

  public TpdmSectionSurveyResponseFactsReference surveyIdentifier(String surveyIdentifier) {
    this.surveyIdentifier = surveyIdentifier;
    return this;
  }

   /**
   * The unique survey identifier from the survey tool.
   * @return surveyIdentifier
  **/
  @ApiModelProperty(example = "null", required = true, value = "The unique survey identifier from the survey tool.")
  public String getSurveyIdentifier() {
    return surveyIdentifier;
  }

  public void setSurveyIdentifier(String surveyIdentifier) {
    this.surveyIdentifier = surveyIdentifier;
  }

  public TpdmSectionSurveyResponseFactsReference link(Link link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(example = "null", value = "")
  public Link getLink() {
    return link;
  }

  public void setLink(Link link) {
    this.link = link;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmSectionSurveyResponseFactsReference tpdmSectionSurveyResponseFactsReference = (TpdmSectionSurveyResponseFactsReference) o;
    return Objects.equals(this.factsAsOfDate, tpdmSectionSurveyResponseFactsReference.factsAsOfDate) &&
        Objects.equals(this.localCourseCode, tpdmSectionSurveyResponseFactsReference.localCourseCode) &&
        Objects.equals(this.schoolId, tpdmSectionSurveyResponseFactsReference.schoolId) &&
        Objects.equals(this.schoolYear, tpdmSectionSurveyResponseFactsReference.schoolYear) &&
        Objects.equals(this.sectionIdentifier, tpdmSectionSurveyResponseFactsReference.sectionIdentifier) &&
        Objects.equals(this.sessionName, tpdmSectionSurveyResponseFactsReference.sessionName) &&
        Objects.equals(this.surveyIdentifier, tpdmSectionSurveyResponseFactsReference.surveyIdentifier) &&
        Objects.equals(this.link, tpdmSectionSurveyResponseFactsReference.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(factsAsOfDate, localCourseCode, schoolId, schoolYear, sectionIdentifier, sessionName, surveyIdentifier, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmSectionSurveyResponseFactsReference {\n");
    
    sb.append("    factsAsOfDate: ").append(toIndentedString(factsAsOfDate)).append("\n");
    sb.append("    localCourseCode: ").append(toIndentedString(localCourseCode)).append("\n");
    sb.append("    schoolId: ").append(toIndentedString(schoolId)).append("\n");
    sb.append("    schoolYear: ").append(toIndentedString(schoolYear)).append("\n");
    sb.append("    sectionIdentifier: ").append(toIndentedString(sectionIdentifier)).append("\n");
    sb.append("    sessionName: ").append(toIndentedString(sessionName)).append("\n");
    sb.append("    surveyIdentifier: ").append(toIndentedString(surveyIdentifier)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

