SELECT SPRIDEN.SPRIDEN_PIDM
FROM SPRIDEN, SGBSTDN
WHERE SPRIDEN.SPRIDEN_PIDM = SGBSTDN.SGBSTDN_PIDM
AND sgbstdn.sgbstdn_coll_code_1 = 'ED'
AND sgbstdn.sgbstdn_degc_code_1 = 'BIS'
AND sgbstdn.sgbstdn_majr_code_1 = 'INTS'
AND SPRIDEN.SPRIDEN_PIDM in (99660, 90039)
ORDER BY SGBSTDN.SGBSTDN_TERM_CODE_EFF;
